### PR TITLE
HF_BOG fixes for spiffs

### PR DESCRIPTION
**Pull request by cjbrigato**
Unless I did not understand the flow, it should do the trick.
As expected, reduces Greatly the complexity.

### CODE REVIEW

**Comment by doegox** [comment]
thanks!

**Comment by doegox** [comment]
I was a bit too quick, that didn't compile. Should be fixed now.

**Comment by cjbrigato** [comment]
I'm definitely sure that one day I'll make a PR that compiles, without an idiot include/prototype missing and such.
But then I will miss my "Unique variable Typo destroy whole PR" effect

**Comment by bogiton** [comment]
Hey! Thanks for this, as well! :)
You guys have made wonders during those 2 months! Congrats!
I can't wait to test SPIFFS, seems so straight-forward.
Maybe that lua script (read_pwd_mem) also needs fixing now?!

**Comment by doegox** [comment]
yeah, it's already... in our todo list :D See issue #285

**Comment by bogiton** [comment]
Ah, yeah, sorry, lots to catch up!
Wish I had time now to help with those. By the time I get some slack, you'll most likely have everything fixed :P

**Comment by iceman1001** [comment]
@bogiton  Feel free to update the lua script...   I havent look at this fix, but before we used 2bytes in the beginning to indicate how many keys that was in.
I guess now with filesize,  we have to divide by keysize instead.

**Comment by alximiktik** [comment]
Hi. i want to sniff keys from our bus terminal(paymant/balance) Can i use Hf_Bog for that? And how to install STANDALONE mods? I have only `LF HID26 standalone - aka SamyRun (Samy Kamkar)`

**Comment by iceman1001** [comment]
A good starting point is  https://github.com/RfidResearchGroup/proxmark3/wiki/Standalone-mode

**Pull request merged**
