### PR TITLE
ISO15693 emulation

### PR DESCRIPTION
**Pull request by markus-oehme-pg40**
I added some functionality to the ISO15693 emulation. Please consider this for inclusion.

### CODE REVIEW

**Comment by iceman1001** [comment]
Interesting one,  I will look into this one.

**Comment by iceman1001** [comment]
On thing that strikes me is,  
we use `-f`  as parameter for filenames.
and why don't you have a `hf 15 eload -f`  where you upload the card memory image to the reserved EMU MEM on device.
and inside your improved sim,  you read that preloaded part of memory?

It will enabled you to get up to 4kb RAM for card memory and it follows the flow of the rest of the pm3 client / device simulation process

**Comment by markus-oehme-pg40** [comment]
> and why don't you have a `hf 15 eload -f` where you upload the card memory image to the reserved EMU MEM on device. and inside your improved sim, you read that preloaded part of memory?
> 
> It will enabled you to get up to 4kb RAM for card memory and it follows the flow of the rest of the pm3 client / device simulation process

That's a good suggestion, I'm going to try to rework this to use a multi-step approach.

**Comment by markus-oehme-pg40** [comment]
I refactored to use the `hf 15 eload` command.

**Comment by iceman1001** [comment]
Excellent,

future improvements would be to read bin/eml/json for the eload.
add commands like esave and eview,

I will merge this PR once the GH actions is done

**Comment by iceman1001** [comment]
@markus-oehme-pg40   you have a minor thing in a printandlogex statement to fix

**Pull request merged**
