### PR TITLE
Edited "protect" help text for more accuracy

### PR DESCRIPTION
**Pull request by Msprg**
Yeah, I got nothing better to do, than just push fixes from discord.

Anyways, I think this should work... I mean It's not like I can break anything by this... 
...
...
**right...?**

Credits more to @tcprst & Jirvin @ Discord than me.

### CODE REVIEW

**Comment by iceman1001** [comment]
Thanks!
It would be even nicer if the text aligned

**Comment by Msprg** [comment]
Oh sorry, have not thought about this for some reason, is this better now?

**Comment by iceman1001** [comment]
Much better,
Thanks

**Comment by Msprg** [comment]
Happy to contribute!

**Pull request merged**
