### PR TITLE
Fixed ledcontrol in SimulateTagLowFrequencyEx

### PR DESCRIPTION
**Pull request by zabszk**
Fixed the issue where SimulateTagLowFrequencyEx in some cases was controlling the LEDs even if ledcontrol argument was set to false.

### CODE REVIEW

**Comment by iceman1001** [comment]
I am curious,  where was the issue when calling `SimulateTagLowFrequencyEx` with ledcontrol false?

**Comment by zabszk** [comment]
> 
> 
> I am curious, where was the issue when calling `SimulateTagLowFrequencyEx` with ledcontrol false?

`ledcontrol` is supposed to determine whether the function should control LEDs or not and that's how it works on lines 858 and 872. If it's set to true then the function turns on and off the LED, if it's set to false then the function doesn't control the LED.

But it is possible that the function executes `goto OUT;` on line 866 and then the LED is always turned off, ignoring the argument `ledcontrol` telling the script to not change the LEDs.

I had this issue in my standalone mode. I set `ledcontrol` to false, because I wanted to control the LEDs myself and in some cases (that goto) the function turns off the LED ignoring the `ledcontrol` being set to false.

**Comment by iceman1001** [comment]
ok,  I haven't seen anyone using ledcontrol before.  Like in seven years. 
To be honest,  I would remove that option since its not used.   I just never got around to do it.

**Comment by zabszk** [comment]
> 
> 
> ok, I haven't seen anyone using ledcontrol before. Like in seven years. To be honest, I would remove that option since its not used. I just never got around to do it.

To be honest I would love to see ledcontrol option in other lfops functions, such as functions used for reading and writing tags. If you work with stadalone mode like I do and these 4 LEDs are the only output you have, it can be sometimes problematic if r/w functions change the LEDs and you can't do anything about it.

**Comment by iceman1001** [comment]
yeah,  either remove it complete or add it to all lf/hf device side commands.  The mix we have been having for ages isn't very good.  A code smell.

I will merge this one and feel free to add led-control to it all ;)

**Comment by iceman1001** [comment]
Thanks!

**Comment by zabszk** [comment]
> 
> 
> yeah, either remove it complete or add it to all lf/hf device side commands. The mix we have been having for ages isn't very good. A code smell.
> 
> I will merge this one and feel free to add led-control to it all ;)

Thanks! I agree that the mix isn't good. I was thinking about adding such argument when I noticed that one function for some reason already have it while the other functions don't.

I will add led control to all other functions.

**Pull request merged**
