### PR TITLE
Update Makefile.defs

### PR DESCRIPTION
**Pull request by blshkv**
Do not overwrite global CC values (if specified in env)

Signed-off-by: Anton Bolshakov <blshkv@users.noreply.github.com>

### CODE REVIEW

**Comment by iceman1001** [comment]
image

looks like `LD` didn't like this suggestion at all...

**Comment by blshkv** [comment]
That basically means that there's a problem with your global LD setting. Sorry, I'm not an expert here. You can leave LD value unchanged then

**Comment by iceman1001** [comment]
... that is our build actions on github...  

I will revert this and let your suggestions be hold until someone who can verify it is available.

**Comment by blshkv** [comment]
The makefile is badly written,
```
 sable: $(OBJS)
-       $(LD) $(LDFLAGS) -o sable $(OBJS) $(LIBS)
+       $(CXX) $(LDFLAGS) -o sable $(OBJS) $(LIBS)
```

**Comment by iceman1001** [comment]
Sadly enough it is out of my league.    Makefile is dark woodoo to me. 

If you have someone who can review it,  let me know

**Pull request merged**
