### PR TITLE
Fix capitalization for command descriptions

### PR DESCRIPTION
**Pull request by sliceratwork**
Just some changes to the command descriptions to make the capitalization consistent.

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice,
However the command.md is autogenerated when we run the `make style` command.
So if you want to see it with capital letters, you will need to modify all command tables.

ref:
https://github.com/RfidResearchGroup/proxmark3/blob/master/Makefile#L251

**Comment by sliceratwork** [comment]
@iceman1001 thank you. I'm still learning.

Will have a look and make another PR.

**Comment by iceman1001** [comment]
Don't take it the wrong way,   we all are learning and Pm3 isn't the easiest code base to jump into.
You can just remove the commands.md from this PR and I can merge.

**Comment by doegox** [comment]
Hmm no, don't delete the commands.md file from the repo :)

**Comment by doegox** [comment]
I restored command.md and merged your PR

**Pull request merged**
