### PR TITLE
New luascript file to format Sector Trailers on the MiFare emulator

### PR DESCRIPTION
**Pull request by nisgola**
Added a new script that writes default or user defined Keys and Access bits to the emulator memory blocks.

### CODE REVIEW

**Comment by iceman1001** [comment]
interesting one...
Try using parameter to the functions  
`
local myfct(sector, block, keya,keyb)
` 

call it with
`
myfct(1, 0, "ffffffffffff", "ffffffffffff")
`

**Comment by nisgola** [comment]
Would it be better to remove the 4K option and just assign all available Sector trailers by default ? Trade emulator memory for code simplicity ?

**Comment by iceman1001** [comment]
the globals isn't nice,
Have you considered skipping the sector loops,  and just just the blocks as base for the loops?

**Comment by iceman1001** [comment]
thanks!

**Pull request merged**
