### PR TITLE
A few extra MF classic keys

### PR DESCRIPTION
**Pull request by borisgolovnev**

### CODE REVIEW

**Comment by iceman1001** [comment]
Cool,
are these static keys or are they from a metro system that makes dynamic keys based on uid for example?
The dictionary wants static keys,   since dynamic keys is connected to one card only.

**Comment by borisgolovnev** [comment]
Good question, I don't really know. Any way to find this out?

**Comment by iceman1001** [comment]
Cool,  cool,
Usually if you have two or more cards from same system,  you can see if the keys are static.

**Comment by borisgolovnev** [comment]
Ok, makes sense.

**Comment by iceman1001** [comment]
did you check the keys on your hotel cards if they were static or?

**Pull request closed without merging**
