### PR TITLE
Add colour to command output

### PR DESCRIPTION
**Pull request by dunderhay**
Added colour to several commands:
`lf hid`
`hf 14a`
`hf mfu`

### CODE REVIEW

**Comment by iceman1001** [comment]
It s gonna be fun looking at these new colors.  Awesome!

**Comment by doegox** [comment]
yeah fun, but wait for phase 2 @iceman1001 :wink:

**Comment by iceman1001** [comment]
What is Phase2 ??

**Comment by iceman1001** [comment]
Hm,   I like seperatation of information. 
Like now UID etc became green  (was yellow before).  and the type is green.
I think  making  the type Yellow will make it easy to see the difference.  ie too much green.

Next thing.  The static nonce line should be:   Static nonce:  red(yes)  | white(no)

image

**Comment by doegox** [comment]
> What is Phase2 ??

image

**Comment by iceman1001** [comment]
Evil.

We most fight this evil.

**Pull request merged**
