### PR TITLE
fix naming convertion messes up

### PR DESCRIPTION
**Pull request by AxisRay**
```
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniff.bin
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniff-5.bin
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniffwefawe
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniffwefawe.bin
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniffwefawe
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniffwefawe-1.bin
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniff.bin1
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniff.bin1
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniff.trace
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniff.trace
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d hf_14asniff.trace
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file hf_14asniff-1.trace
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d ....hf_14asniff.trace
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file ....hf_14asniff.trace
[usb] pm3 --> mem spiff dump -s hf_14asniff.trace -d ....hf_14asniff.trace
[=] downloading 1390 bytes from `hf_14asniff.trace` (spiffs)
[+] saved 1390 bytes to binary file -1....hf_14asniff.trace
```
seems better😀

### CODE REVIEW

**Comment by AxisRay** [comment]
……gcc 10.3 passed

**Comment by doegox** [comment]
Your code in CmdFlashMemSpiFFSDump doesn't make sense.
memccpy with wrong args, new_fn defined but not used,...
See also filenamemcopy and newfilenamemcopy in client/src/fileutils.c, this should help.

**Comment by AxisRay** [comment]
Oh, so stupid.
I must be asleep.

**Comment by AxisRay** [comment]
Anything else need I do before merge?

**Pull request merged**
