### PR TITLE
More lists to brute foruce RFID cards

### PR DESCRIPTION
**Pull request by will-caruana**
Lists of most common English words and most common passwords along with two lists of ASCII numbers in hex and an additional iClass list that is based off patterns seen in other default password lists.

### CODE REVIEW

**Comment by iceman1001** [comment]
is it ready for merging?  or ?

**Comment by will-caruana** [comment]
Yes sorry for the mistakes Vortix looked it over also and its good for merging.

**Comment by BaseZoubru** [comment]
Hello everyone, sorry if I'm wrong because I'm novice, but all the dictionary called "6_byte..." are only 5 bytes actually. Is it right? As I know very few things on this topic I'm totally lost.

**Comment by BaseZoubru** [comment]
Hello everyone, I'm looking for "Urmet" tag's keys, I found only one called "FDI" inside the mfc_default_keys.dic :
# Data from FDi tag
8829DA9DAF76

Someone could help me please? 

kind regards

Zoubru

**Comment by iceman1001** [comment]
Run that card only key recovering commands and extract all keys?   ie:  `hf mf autopwn`

**Pull request merged**
