### PR TITLE
Bruteforce engine to crack non-random 32 bit keys

### PR DESCRIPTION
**Pull request by phaseloop**
This PR introduces an integrated and extendable bruteforce engine used to crack keys which were generated using non-random or broken way.

According to various service manuals - a lot of vendors (car washes, vending machines, etc) during installation ask user to provide a PIN or short password which is then used as key for all RFID cards used in particular system/area. We aim to crack those keys by iterating over small key spaces based on ASCII characters. Few dictionaries available in proxmark3 repository already utilize partially this mechanism.

Currently this bruteforce mode is implemented for em4x50 cards - with Mifare classic coming soon + additional "smart" cracking mode.

Examples:

` lf em 4x50 brute --mode range --begin 12330000 --end 12340000` -> tries pwds from 0x12330000 to 0x12340000

this mode was already implemented for em4x50 and was included as "range" mode in the bruteforce engine.

 `lf em 4x50 brute --mode charset --digits --uppercase` -> tries all combinations of keys comprised of ASCII codes for digits and uppercase letters

Performance: about few minutes for searching digits character, about 4h for searching all uppercase ASCII characters. Password cracking for em4x50 is about 27 keys/sec

### CODE REVIEW

**Comment by iceman1001** [comment]
A interesting refactoring of the bruteforcer impl.   Nice!

May I suggest you remove the command.json/md  files in this PR,  so I can merge it.   
I will run `make style` anyway after a bunch more merging of PRs.

**Comment by iceman1001** [comment]
ping @phaseloop

**Comment by phaseloop** [comment]
done, thanks :). I'll start working on generator for mifare classic.

**Comment by iceman1001** [comment]
`bzero`   call will need to be addressed,   

Use `memset`  instead

**Comment by phaseloop** [comment]
done, weird that windows build fails on that but ok :)

**Comment by iceman1001** [comment]
Awesome!

**Pull request merged**
