### PR TITLE
[WIP] Zlib->LZ4 change

### PR DESCRIPTION
**Pull request by slurdge**

### CODE REVIEW

**Comment by iceman1001** [comment]
Should the Get_lz4.sh  enforce INLINE on deviceside?   I think @doegox  mentioned we optimize for size,  hence inline is useless on deviceside.

And if we change fpga_compress...  we would need to fix the hardnested tables file which uses zlib

**Comment by slurdge** [comment]
@iceman1001 i played with the inlines and the current situation is what gets the smallest size, just removing it for decrompress_generic.

**Comment by doegox** [comment]
> And if we change fpga_compress... we would need to fix the hardnested tables file which uses zlib

For hardnested tables, zlib is used in the client and the OS zlib is used if available, I don't see an urge to change that part

**Comment by doegox** [comment]
Ha yes I forgot fpga_compress is also compressing hardnested tables. But why is it so ??

**Comment by iceman1001** [comment]
You have to as Piwi about that.  It uses compression to make all tables smaller (obviously),  and  fpga_compress already did that on files,  so I guess he thought reusing it was easier than making a new tool for that purpose

**Comment by iceman1001** [comment]
ok, with some casting, I got it to compile.
ran a lua script ,  which runs  'lf fdx read' , 'hf 14a info'  ten times with two cards (lf,hf) on the Pm3.
```
Master:
iceman@GNU:~/p1$ time ./pm3 -l 1
real    0m27.537s
user    0m0.125s
sys     0m0.328s

Slurdge:
iceman@GNU:~/slurdge$ time ./pm3 -l 1
real    0m24.252s
user    0m0.141s
sys     0m0.281s
```

That is 3 seconds difference.  Cool!

**Comment by doegox** [comment]
> _this is done when creating hardnested tables. Remember you asked him about documentation and didn't get some answers_ We don't re-create those tables. So I guess we are fine.

Well we can recompress them...
I tested bzip2 with default options, tables become 7x smaller than with the zlib super tuned pm3 version.

**Comment by doegox** [comment]
> ran a lua script , which runs 'lf fdx read' , 'hf 14a info' ten times with two cards (lf,hf) on the Pm3.

To minimize overhead you can try with `hf tune 1` and `lf tune n 1`

**Comment by doegox** [comment]
I tried same amount of interleaved and non-interleaved operations. My estimate is:
* 1 FPGA reflashing zith ZLIB: 1.11s
* 1 FPGA reflashing zith LZ4: 0.96s

**Comment by iceman1001** [comment]
> To minimize overhead you can try with hf tune 1 and lf tune n 1
I love the inconsistency..  1 vs n 1. ,  but that is smooth way to test.

Got  26sec vs 22sec. 

Didn't @slurdge mention 20-30% speed ups?

**Comment by slurdge** [comment]
Yeah, I timed the upload directly on the board. When timing from client, it's skewed. Still it's 15% from client side.

**Comment by iceman1001** [comment]
I guess with all changes,  like bigbuff / stack and compressing transfers we still get a decent speed up.
15% from client isn't bad at all.

It compiles on my WSL now.

**Comment by doegox** [comment]
> To minimize overhead you can try with hf tune 1 and lf tune n 1

Haha I knew you'd be triggered on that one :) I was too.

BTW I pushed a bzip2 branch to test hardnested, so we can get rid of zlib entirely and remove hardnested compression from fpga_compress. Still need to figure out the new bz2 dep on all platforms... Feel free to test

**Comment by iceman1001** [comment]
The question is if this PR is ready to merge?

**Comment by doegox** [comment]
I'd say yes, good enough for merge.
@slurdge anything essential to do before the merge ?

**Comment by iceman1001** [comment]
Besides a CHANGELOG.md line,   and a longing wish for documentation of this in a notes.md file,   I am fine with merging.,

**Pull request merged**
