### PR TITLE
Create hf-writer.lua

### PR DESCRIPTION
**Pull request by Windslab**
Dear,

I wish to invest this script to comunity and delete it from my repo. All members should manage next it destiny.

My opinion that we can to do in future:
* Add support another types of dumps: `BIN`, `JSON`
* Add undependence from the operation system. At the moment code not working in Linux.
* Add more chinesse backdoors RAW commands for UID changing (find RAW for the 4 byte familiar chinese card, from native it soft: http://bit.ly/39VIDsU)
* Hide system messages when you writing a dumps, replace it to some of like [#####----------] 40%

Will be happy to see a video for code optimization with comments at your YouTube channel.

Many Thanks,
Best Regards

### CODE REVIEW

**Comment by iceman1001** [comment]
Good!
let me suggest that you start renaming your script to match what it actually does.
your name **hf - write**  indicates High Frequence Writer,   which isn't at all what your script does.
Your script seem to be targetting a certain kind of magic cards for Mifare Classic,  where it restore / load a file dump on to the card.   And possible lock / change uid.

If you have look at the existing lua scripts,  you will find that they all follow a certain style.
I strongly suggest you modify your script to follow that certain style. 

And finally,  keep up the nice work.  
Its a start and it can only become better.

**Comment by Windslab** [comment]
It's exactly duing how is named. Directly writing an `eml` files to hf card with optionaly UID changing of them. Yes it's can be better, that why it there. Unfortunately I not programmist...

**Comment by Windslab** [comment]
PS: Do you will add it to the `luascripts`? Didn't get that's moment. Please answer.

If not you should think how you can fast reproduce the subway card's with commands. That's made for it.

**Comment by iceman1001** [comment]
I will merge when you adapted your script to the coding standards here.  I already gave you instructions on what to improve.

**Comment by Windslab** [comment]
Please find new changes at the commits

**Comment by iceman1001** [comment]
Good, much better.
Now you need to add the possibility for a **-h** helptext param....

**Comment by Windslab** [comment]
There you go!

**Comment by iceman1001** [comment]
I will rename the file later to fit its purpose better.

**Comment by Windslab** [comment]
Okay and please help to optimise a script code.
You will do this perfectly and nice lesson for me.

Many Thanks,
Best Regards
Yevgeny

чт, 19 мар. 2020 г. в 13:25, Iceman <notifications@github.com>:

**Pull request merged**
