### PR TITLE
Fix the lf sampling when bits_per_sample is less than 8

### PR DESCRIPTION
**Pull request by wh201906**
This PR will make bps<8 work, which saves ROM for longer sample time.
This bug exists for a long time. 
***
This is the data graph before this fix
(bps=5, all data are messed up)
image

(bps=8, the expected waveform shape)
image
***
This is the data graph after this fix and PR #1879
(bps=5, the expected waveform shape)
image

The sample count is also bigger 
image

### CODE REVIEW

**Comment by wh201906** [comment]
I'm not sure if the workaround in https://github.com/RfidResearchGroup/proxmark3/pull/1880/commits/f4879fdc172f43bf965a29f2420f7c42030e895c is good, or I should rewrite these functions.

**Comment by iceman1001** [comment]
Good question,   The removal of the offset and compute signal properties should be applied to the signal regardless what it takes.

I can merge this PR,  and you can make the rewrite of them?

**Comment by wh201906** [comment]
I will try to do this, but I don't know not how to do this now, so it might take some time. I'd appreciate it if someone can help me or just make a new PR for it.
By the way, I wonder the meaning of the `ON_DEVICE` macro there.
https://github.com/RfidResearchGroup/proxmark3/blob/master/common/lfdemod.c#L160

**Comment by iceman1001** [comment]
that code is shared and is used in both ARMSRC and CLIENT.    
the if-case means that it is NOT on device,  ie client side.

**Comment by wh201906** [comment]
I got it. Thanks!

**Pull request merged**
