### PR TITLE
StaticNested fast decrypt(backdoor 2nt.).

### PR DESCRIPTION
**Pull request by xianglin1998**
Look what I found...
Wow, is fast decrypt staticnested :)
Hahahahaha, this is a very big advance.

image
image

### CODE REVIEW

**Comment by iceman1001** [comment]
Interesting find!
Nonce distance 161.   Is that true for all static nonce cards?

**Comment by iceman1001** [comment]
Tried it and its fast.

**Comment by xianglin1998** [comment]
> Tried it and its fast.

Haha, yes its fast.

**Comment by xianglin1998** [comment]
> Interesting find! Nonce distance 161. Is that true for all static nonce cards?

After test, we found some nt1_1 must use distance 161 to recover ks1, so my source code have the "if nt == 0x????"(So is only some tag, not all tag).

**Comment by xianglin1998** [comment]
> > Interesting find! Nonce distance 161. Is that true for all static nonce cards?
> 
> After test, we found some nt1_1 must use distance 161 to recover ks1, so my source code have the "if nt == 0x????"(So is only some tag, not all tag).

And must auth keyb.

**Comment by iceman1001** [comment]
OK,  you are doing three auths,  and use the found potential key candidate lists to find a match from those.
Combining the older key recovery concepts.  Cool idea and great find!

**Comment by iceman1001** [comment]
I see,   its the same concept as the normal nested attack,  but you changed the nonce collecting to three auths and using the last two nested auth nonces.

**Comment by xianglin1998** [comment]
> 

Yes, you are right. 
Why staticnested its so slow?
Because there is only one set of encrypted NT, so we can't use normal nested to decrypt and get some keys （group）.
For normal staticnested tag, We only can get 0 -> 100K or more keys, no keys control group to uniquesort and find the same.

**Comment by xianglin1998** [comment]
> I see, its the same concept as the normal nested attack, but you changed the nonce collecting to three auths and using the last two nested auth nonces.

Yes, you are right.
Why staticnested its so slow?
Because there is only one set of encrypted NT, so we can't use normal nested to decrypt and get some keys （group）.
For normal staticnested tag, We only can get 0 -> 100K or more keys, no keys control group to uniquesort and find the same.

**Comment by xianglin1998** [comment]
> > I see, its the same concept as the normal nested attack, but you changed the nonce collecting to three auths and using the last two nested auth nonces.
> 
> Yes, you are right. Why staticnested its so slow? Because there is only one set of encrypted NT, so we can't use normal nested to decrypt and get some keys （group）. For normal staticnested tag, We only can get 0 -> 100K or more keys, no keys control group to uniquesort and find the same.

Why decrypt staticnested is so fast, yes....
We have two encrypted NT, that is no same nt.
So we can decrypt 1 keys gruop from nt1 and decrypt 1 keys group from nt2, to uniquesort and find same key in group1 and group2.

**Comment by xianglin1998** [comment]
> 

This is fast decrypt staticnested core.
The fast decryption staticnested is essentially a normal decryption of nested decryption.
Because we have 2 encrypted  nt, the staticnested is never 'static'...
LoL...

**Comment by xianglin1998** [comment]
> > > I see, its the same concept as the normal nested attack, but you changed the nonce collecting to three auths and using the last two nested auth nonces.
> > 
> > 
> > Yes, you are right. Why staticnested its so slow? Because there is only one set of encrypted NT, so we can't use normal nested to decrypt and get some keys （group）. For normal staticnested tag, We only can get 0 -> 100K or more keys, no keys control group to uniquesort and find the same.
> 
> Why decrypt staticnested is so fast, yes.... We have two encrypted NT, that is no same nt. So we can decrypt 1 keys gruop from nt1 and decrypt 1 keys group from nt2, to uniquesort and find same key in group1 and group2.

This is fast decrypt staticnested core.
The fast decryption staticnested is essentially a normal decryption of nested decryption.
Because we have 2 encrypted nt, the staticnested is never 'static'...
LoL...

**Comment by xianglin1998** [comment]
Special notes:

There are two levels of staticnested tags in China. The level1 is our common staticnested tag. When decrypting this level1 tag, the initial dist is fixed at 160. It can be decrypted using both RRG firmware and PM3 official firmware. The level2 is uncommon. When level2 tag decrypting key B, it must use the initial dist of 161, otherwise it cannot decrypt a valid secret key, this is why you see the logic of 'if level == 2: dist = 161' in the code.

**Comment by iceman1001** [comment]
Interesting,  testing out and adapting your implementation,     Its almost like the slowest part is the checkkeys :)  
Amazing improvement you have done. 

```
[usb|script] pm3 --> hf mf staticnested --1k --blk 0 -a -k ffffffffffff
[#] 1 static nonce 01200145
[=] RDV4 with flashmemory supported detected.
[+] Testing known keys. Sector count 16
[=] ...
[=] Chunk 6.8s | found 3/32 keys (43)
[+] Time to check 42 known keys: 7 seconds

[+] enter static nested key recovery
[+] Found 1 key candidates

[+] target block:   4 key type: A  -- found valid key [ FFFFFFFFFF01 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:   8 key type: A  -- found valid key [ FFFFFFFFFF02 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:  12 key type: A  -- found valid key [ FFFFFFFFFF03 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:  16 key type: A  -- found valid key [ FFFFFFFFFF04 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:  20 key type: A  -- found valid key [ FFFFFFFFFF05 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:  24 key type: A  -- found valid key [ FFFFFFFFFF06 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:  28 key type: A  -- found valid key [ FFFFFFFFFF07 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:  32 key type: A  -- found valid key [ FFFFFFFFFF08 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:  36 key type: A  -- found valid key [ FFFFFFFFFF09 ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 2 key candidates

[+] target block:  40 key type: A  -- found valid key [ FFFFFFFFFF0A ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 2 key candidates

[+] target block:  44 key type: A  -- found valid key [ FFFFFFFFFF0B ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:  48 key type: A  -- found valid key [ FFFFFFFFFF0C ]
[=] Chunk 0.5s | found 2/32 keys (1)
[#] Card didn't answer to CL1 select all
[+] Found 1 key candidates

[+] target block:  56 key type: A  -- found valid key [ FFFFFFFFFF0E ]
[=] Chunk 0.5s | found 2/32 keys (1)
[+] Found 1 key candidates

[+] target block:   0 key type: B  -- found valid key [ 11FF22FF33FF ]
[=] Chunk 0.4s | found 1/32 keys (1)
[+] Found 1 key candidates

[+] target block:  52 key type: B  -- found valid key [ FFFFFFFFFFD0 ]
[=] Chunk 0.4s | found 1/32 keys (1)
[+] time in static nested 22 seconds

[=] trying to read key B...

[+] found keys:

[+] -----+-----+--------------+---+--------------+----
[+]  Sec | Blk | key A        |res| key B        |res
[+] -----+-----+--------------+---+--------------+----
[+]  000 | 003 | FFFFFFFFFFFF | 1 | 11FF22FF33FF | 1
[+]  001 | 007 | FFFFFFFFFF01 | 1 | FFFFFFFFFF10 | 1
[+]  002 | 011 | FFFFFFFFFF02 | 1 | FFFFFFFFFF20 | 1
[+]  003 | 015 | FFFFFFFFFF03 | 1 | FFFFFFFFFF30 | 1
[+]  004 | 019 | FFFFFFFFFF04 | 1 | FFFFFFFFFF40 | 1
[+]  005 | 023 | FFFFFFFFFF05 | 1 | FFFFFFFFFF50 | 1
[+]  006 | 027 | FFFFFFFFFF06 | 1 | FFFFFFFFFF60 | 1
[+]  007 | 031 | FFFFFFFFFF07 | 1 | FFFFFFFFFF70 | 1
[+]  008 | 035 | FFFFFFFFFF08 | 1 | FFFFFFFFFF80 | 1
[+]  009 | 039 | FFFFFFFFFF09 | 1 | FFFFFFFFFF90 | 1
[+]  010 | 043 | FFFFFFFFFF0A | 1 | FFFFFFFFFFA0 | 1
[+]  011 | 047 | FFFFFFFFFF0B | 1 | FFFFFFFFFFB0 | 1
[+]  012 | 051 | FFFFFFFFFF0C | 1 | FFFFFFFFFFC0 | 1
[+]  013 | 055 | ------------ | 0 | FFFFFFFFFFD0 | 1
[+]  014 | 059 | FFFFFFFFFF0E | 1 | FFFFFFFFFFE0 | 1
[+]  015 | 063 | FFFFFFFFFFFF | 1 | FFFFFFFFFFFF | 1
[+] -----+-----+--------------+---+--------------+----
[+] ( 0:Failed / 1:Success )

```

**Comment by iceman1001** [comment]
the question is why you kept the old impl.  it seems not to serve any purpose anymore.

**Comment by xianglin1998** [comment]
> the question is why you kept the old impl. it seems not to serve any purpose anymore.

I'm afraid some cards can't get two groups of encrypted NT. If they do, the old logic may help me.

**Comment by xianglin1998** [comment]
> Interesting, testing out and adapting your implementation, Its almost like the slowest part is the checkkeys :) Amazing improvement you have done.
> 
> ```
> [usb|script] pm3 --> hf mf staticnested --1k --blk 0 -a -k ffffffffffff
> [#] 1 static nonce 01200145
> [=] RDV4 with flashmemory supported detected.
> [+] Testing known keys. Sector count 16
> [=] ...
> [=] Chunk 6.8s | found 3/32 keys (43)
> [+] Time to check 42 known keys: 7 seconds
> 
> [+] enter static nested key recovery
> [+] Found 1 key candidates
> 
> [+] target block:   4 key type: A  -- found valid key [ FFFFFFFFFF01 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:   8 key type: A  -- found valid key [ FFFFFFFFFF02 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  12 key type: A  -- found valid key [ FFFFFFFFFF03 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  16 key type: A  -- found valid key [ FFFFFFFFFF04 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  20 key type: A  -- found valid key [ FFFFFFFFFF05 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  24 key type: A  -- found valid key [ FFFFFFFFFF06 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  28 key type: A  -- found valid key [ FFFFFFFFFF07 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  32 key type: A  -- found valid key [ FFFFFFFFFF08 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  36 key type: A  -- found valid key [ FFFFFFFFFF09 ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 2 key candidates
> 
> [+] target block:  40 key type: A  -- found valid key [ FFFFFFFFFF0A ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 2 key candidates
> 
> [+] target block:  44 key type: A  -- found valid key [ FFFFFFFFFF0B ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  48 key type: A  -- found valid key [ FFFFFFFFFF0C ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [#] Card didn't answer to CL1 select all
> [+] Found 1 key candidates
> 
> [+] target block:  56 key type: A  -- found valid key [ FFFFFFFFFF0E ]
> [=] Chunk 0.5s | found 2/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:   0 key type: B  -- found valid key [ 11FF22FF33FF ]
> [=] Chunk 0.4s | found 1/32 keys (1)
> [+] Found 1 key candidates
> 
> [+] target block:  52 key type: B  -- found valid key [ FFFFFFFFFFD0 ]
> [=] Chunk 0.4s | found 1/32 keys (1)
> [+] time in static nested 22 seconds
> 
> [=] trying to read key B...
> 
> [+] found keys:
> 
> [+] -----+-----+--------------+---+--------------+----
> [+]  Sec | Blk | key A        |res| key B        |res
> [+] -----+-----+--------------+---+--------------+----
> [+]  000 | 003 | FFFFFFFFFFFF | 1 | 11FF22FF33FF | 1
> [+]  001 | 007 | FFFFFFFFFF01 | 1 | FFFFFFFFFF10 | 1
> [+]  002 | 011 | FFFFFFFFFF02 | 1 | FFFFFFFFFF20 | 1
> [+]  003 | 015 | FFFFFFFFFF03 | 1 | FFFFFFFFFF30 | 1
> [+]  004 | 019 | FFFFFFFFFF04 | 1 | FFFFFFFFFF40 | 1
> [+]  005 | 023 | FFFFFFFFFF05 | 1 | FFFFFFFFFF50 | 1
> [+]  006 | 027 | FFFFFFFFFF06 | 1 | FFFFFFFFFF60 | 1
> [+]  007 | 031 | FFFFFFFFFF07 | 1 | FFFFFFFFFF70 | 1
> [+]  008 | 035 | FFFFFFFFFF08 | 1 | FFFFFFFFFF80 | 1
> [+]  009 | 039 | FFFFFFFFFF09 | 1 | FFFFFFFFFF90 | 1
> [+]  010 | 043 | FFFFFFFFFF0A | 1 | FFFFFFFFFFA0 | 1
> [+]  011 | 047 | FFFFFFFFFF0B | 1 | FFFFFFFFFFB0 | 1
> [+]  012 | 051 | FFFFFFFFFF0C | 1 | FFFFFFFFFFC0 | 1
> [+]  013 | 055 | ------------ | 0 | FFFFFFFFFFD0 | 1
> [+]  014 | 059 | FFFFFFFFFF0E | 1 | FFFFFFFFFFE0 | 1
> [+]  015 | 063 | FFFFFFFFFFFF | 1 | FFFFFFFFFFFF | 1
> [+] -----+-----+--------------+---+--------------+----
> [+] ( 0:Failed / 1:Success )
> ```

In order to reduce the loss of flash, I specially replaced the process of check keys with direct communication..

**Comment by iceman1001** [comment]
loss of flash?   The flash usage was meant for large candidate lists.   This new technique renders you very few candidates.
anything less 70 (6*70=420b)  candidates can be tested with the normal fchk function since it fits in one usbcommand.   I saw you limited to 10.   

Which cards have you seen which don't give you two encrypted nonces?

**Comment by iceman1001** [comment]
I reworked your impl a bit,    https://asciinema.org/a/501090

**Comment by xianglin1998** [comment]
> 

After my test, I have never seen a staticnested tag that does not give two encrypted NT. Theoretically, fast decrypt staticnested can work on 99% of the staticnested tag in earth. Ha ha ha.

**Comment by xianglin1998** [comment]
> 

Wow, cool!!!

**Comment by iceman1001** [comment]
yeah,  so I clean stuff up,   if you want to look at it,   but first I will merge this one in order for your eternal glory in the git history and CHANGELOG.md  :)

Speaking of which,   you need to add a line in CHANGELOG.md

**Comment by xianglin1998** [comment]
Higher performance and better user experience need your improvement. Thank Iceman.

**Comment by iceman1001** [comment]
Thank you for this amazing new thinking on a problematic card.  I am impressed you found a way to get two different nonces.

**Comment by xianglin1998** [comment]
> yeah, so I clean stuff up, if you want to look at it, but first I will merge this one in order for your eternal glory in the git history and CHANGELOG.md :)
> 
> Speaking of which, you need to add a line in CHANGELOG.md



> 

In China, someone found this vulnerability in the chip reverse of staticnested tag and implemented it on pn532. He used rfidtools but did not open source. Therefore, I used rdv4 sniff to communicate with him. At first, I thought it was a backdoor instruction similar to gen1a, which was so fast that it was as fast as reading the key directly. However, after my review, sniff log told me, There is no back door instruction similar to gen1a. After careful examination, I found that there is a verification process repeated three times during the communication process. So far, I have found the core of this vulnerability.

**Comment by xianglin1998** [comment]
> > yeah, so I clean stuff up, if you want to look at it, but first I will merge this one in order for your eternal glory in the git history and CHANGELOG.md :)
> > Speaking of which, you need to add a line in CHANGELOG.md
> 
> > 
> 
> In China, someone found this vulnerability in the chip reverse of staticnested tag and implemented it on pn532. He used rfidtools but did not open source. Therefore, I used rdv4 sniff to communicate with him. At first, I thought it was a backdoor instruction similar to gen1a, which was so fast that it was as fast as reading the key directly. However, after my review, sniff log told me, There is no back door instruction similar to gen1a. After careful examination, I found that there is a verification process repeated three times during the communication process. So far, I have found the core of this vulnerability.



> > yeah, so I clean stuff up, if you want to look at it, but first I will merge this one in order for your eternal glory in the git history and CHANGELOG.md :)
> > Speaking of which, you need to add a line in CHANGELOG.md
> 
> > 
> 
> In China, someone found this vulnerability in the chip reverse of staticnested tag and implemented it on pn532. He used rfidtools but did not open source. Therefore, I used rdv4 sniff to communicate with him. At first, I thought it was a backdoor instruction similar to gen1a, which was so fast that it was as fast as reading the key directly. However, after my review, sniff log told me, There is no back door instruction similar to gen1a. After careful examination, I found that there is a verification process repeated three times during the communication process. So far, I have found the core of this vulnerability.

I am not the first discoverer, but I discovered that the first discoverer implemented it on the closed source rfidtools, so I reversed it and opened it up.

**Comment by iceman1001** [comment]
Since you work with both rfidtools and this project,  I am grateful regardless.  It is a great contribution.

If you on discord,  we can chat about the differences I have made and you can test it on your cards since I don't have that special 161 card to test.

**Comment by xianglin1998** [comment]
> 

OK, no problem, i can test after your pr.

**Comment by xianglin1998** [comment]
> yeah, so I clean stuff up, if you want to look at it, but first I will merge this one in order for your eternal glory in the git history and CHANGELOG.md :)
> 
> Speaking of which, you need to add a line in CHANGELOG.md

Tomorrow, I will carefully study how to add a line of changelog correctly, which is a very honorable thing.

**Comment by iceman1001** [comment]
haha,  not that hard.  I will do it for you now.

**Comment by xianglin1998** [comment]
> 

thanks.

**Comment by iceman1001** [comment]
@xianglin1998   here my patch file for my changes.   Remove the .txt to make it into a git patch file.
See if you can test it against latest source with your other cards

[ice_static.patch.txt](https://github.com/RfidResearchGroup/proxmark3/files/8885820/ice_static.patch.txt)

**Comment by xianglin1998** [comment]
> @xianglin1998 here my patch file for my changes. Remove the .txt to make it into a git patch file. See if you can test it against latest source with your other cards
> 
> [ice_static.patch.txt](https://github.com/RfidResearchGroup/proxmark3/files/8885820/ice_static.patch.txt)

Your patch can't work for staticnested level2.
image

**Comment by xianglin1998** [comment]
image
image

Look, at present, only the KeyA of level2 tag can be recovered, because the KeyB of level2 tag must be using 'prng_successor(nt1, 161)' to recover the first group of target_nt, and the second group of target_nt must be using 'prng_successor(nt1, 321)' to recover. dist starts from 161, and 161 + 160 = 321dist.(Only level2 and auth type == keyB)

**Comment by xianglin1998** [comment]
I fixed the problem that level2 could not work because should judge the 'targetType == 1' and use dist 161 and 321.

[armfix.patch.txt](https://github.com/RfidResearchGroup/proxmark3/files/8887651/armfix.patch.txt)

This is my change on arm(you can direct modify your code.)
image
image

image

**Comment by iceman1001** [comment]
@xianglin1998 ,  I pushed my minor changes to the repo.

If you can test it against that 9080a2 keyB to see if it works like it should?

**Comment by xianglin1998** [comment]
@iceman1001 Can't work, your 'pre-generate nonces' logic have some problem, should to use 'targetKeyType', not 'keyType'.
image

**Comment by xianglin1998** [comment]
After change to 'targetKeyType', all tag work.

**Comment by iceman1001** [comment]
aha,   I see my mistake.    Pushed a fix for it.   
Thanks!

I think when you run it now,  it looks good both in autopwn and staticnested,   and the code is a bit cleaner.
performance is more or less the same.   I thought I could make only three auths in one go but I didn't get there quite yet

**Comment by xianglin1998** [comment]
OH, NICE!!!
This may already be perfect. COOL!!!

**Comment by iceman1001** [comment]
Its all thanks to you!

**Pull request merged**
