### PR TITLE
fix: #520 - free mutex after work is done

### PR DESCRIPTION
**Pull request by h4waii**
Why not just free after key found or not found?

### CODE REVIEW

**Comment by iceman1001** [comment]
dunno,  I guess it might be calling generate candidates several times?

**Comment by h4waii** [comment]
Would it make sense to free them at https://github.com/RfidResearchGroup/proxmark3/blob/cfcb0494590d8dbe611e9e1eaf60f52495fd69de/client/cmdhfmfhard.c#L2258 after a key isn't found but the work continues?

Adding the destroy at these sections did not cause any appreciable slowdown on aarch64 or x86_64 for me, but I did **not** measure possible contention.

**Comment by iceman1001** [comment]
destroying / creating a mutex isn't time consuming.

**Comment by h4waii** [comment]
I added a free inside both if statements at line 2258 and 2385, as well as after work is complete with key or no key found.

I do not know if this is correct, but it makes sense in my head, compiles, and runs successful on both x86_64 and aarch64 /arm8 / Android now.

**Comment by iceman1001** [comment]
sounds good to me.  Push your latest patches in this PR and I merge it.

**Comment by iceman1001** [comment]
bugger,  this breaks the hardnested when running second time.

**Pull request merged**
