### PR TITLE
Add cmake support to client. Restructure project to see dependencies.

### PR DESCRIPTION
**Pull request by bkerler**
Fixed recursive header in hfmfhard, added cmake support to client. Restructured project to see dependencies.

### CODE REVIEW

**Comment by bkerler** [comment]
Made a clean checkout to confirm everything builds fine. It does now :)

**Comment by doegox** [comment]
it seems to fail on Windows https://ci.appveyor.com/project/RfidResearchGroup/proxmark3/builds/32199249
```
[-] CC src/proxmark3.c
bash : cc1.exe: error: ./deps/include: not a directory [-Werror]
At line:11 char:1
+ bash -c -i 'pwd;make clean;make all'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (cc1.exe: error:...ctory [-Werror]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
cc1.exe: error: ./deps/common: not a directory [-Werror]
In file included from src/proxmark3.c:12:
src/proxmark3.h:15:10: fatal error: common.h: No such file or directory
   15 | #include "common.h"
      |          ^~~~~~~~~~
cc1.exe: all warnings being treated as errors
compilation terminated.

```

**Comment by iceman1001** [comment]
I suggest waiting with this PR,  we will push some preference functions first, then make a release/tag,  and after that,  this one would fit.

**Comment by bkerler** [comment]
Sounds good to me.

**Comment by bkerler** [comment]
It does fail on windows currently due to windows not supporting links. Will have a look at it.

**Comment by doegox** [comment]
next one:
```
[-] CC src/mifare/desfire_crypto.c
bash : src/mifare/desfire_crypto.c:38:10: fatal error: ../../deps/common/crc32.h: No such file or directory
At line:11 char:1
+ bash -c -i 'pwd;make clean;make all'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (src/mifare/desf...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   38 | #include "../../deps/common/crc32.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by bkerler** [comment]
Already on it :) I'm an old man, I'm not that fast :D

**Comment by bkerler** [comment]
Great. Now everything seems fine :)

**Comment by doegox** [comment]
btw just an advice: propose your changes in a separate branch of yours, so your master is not stuck waiting for us to merge. Then you can rewind your master and keep following the rrg repo master. It avoids messy situations.

**Comment by doegox** [comment]
I went through a diff between your PR and current master and I see the following:
1. New cmake gears, obviously
2. Reorganizing source files
3. make style
4. changes in client/deps/cliparser/cliparser.c (removing fflush, removing error message)
5. removal of client/fido/fido2.json

That's a lot for a single PR, that's why it's better to keep the master always in sync with rrg master.
What we can do:
1. cmake additions will be postponed a little bit as explained by @iceman1001 
2. your reorganization makes sense and it's better to do it before tagging so I'll incorporate it now
3. I'll push a make style on master, it will reduce the diffs introduced by your PR, our fault, we should do it more often. This introduces a little conflict in cliparser, nothing bad but don't worry if you see your PR conflicting
4. talking about cliparser, can you explain why you want to introduce these changes?
5. client/fido/fido2.json needs to appear again. I'll reintroduce it while reorganizing the dirs. Actually we've an internal issue to move it to sth like resources/fido2_defparams.json, that will be done later but meanwhile we can't just delete it.

**Comment by bkerler** [comment]
Cliparser and fido changes must have happened on conflict merge. I didn't change anything there. I will have a look at it.

**Comment by doegox** [comment]
amiitool/key_retail.bin disappeared also
but don't worry, I'm on it

**Comment by doegox** [comment]
ok so far:
* your directory reorganisation is pushed in https://github.com/RfidResearchGroup/proxmark3/tree/reorgdirs  If it compiles fine on travis & appveyor, I'll merge it
* on top of it, your cmake is pushed in https://github.com/RfidResearchGroup/proxmark3/tree/newcmake

reorgdirs compiles fine on my side
I didn't test cmake

What I didn't include from your PR:
* I preserved amiitool/key_retail.bin
* I preserved client/src/fido/fido2.json
* I didn't include the changes in deps/cliparser/cliparser.c
* I didn't include the symlinks 
   * client/deps/common -> ../../common
   * client/deps/include -> ../../include

For the symlinks, do you still need them ? I remember you had to find a workaround for the windows compilation anyway, and current Makefile works fine without them. Do you need them for cmake ? If yes, can we avoid having symlinks and find another way ?

If you want to work further on the cmake, I suggest you fetch the rrg newcmake branch and you create your own branch on top of it and PR your changes.

**Comment by bkerler** [comment]
Sound pretty good to me. Symlinks shouldn't be necessary anymore. Thanks for doing the changes/fixes ;)

**Comment by doegox** [comment]
Great !
I'll close this one.

**Comment by doegox** [comment]
I opened https://github.com/RfidResearchGroup/proxmark3/issues/693 for further discussions

**Comment by bkerler** [comment]
To completely close this one: CMAKE works fine after your changes. So everything ok :)

**Pull request closed without merging**
