### PR TITLE
fc/cn support for iclass encode

### PR DESCRIPTION
**Pull request by bettse**
Pretty sure this isn't quite right (like, I think it works, but I think it isn't good code).  I wanted to open this to start getting feedback.  

 * More correct way to copy data to 'credential'
 * Should I support --format?
 * Is using `bin_len` an OK way to determine if the user is using --bin vs --fc/--cn ?

### CODE REVIEW

**Comment by tcprst** [comment]
Looks like you have H10301 hardcoded as the wiegand format.  Other commands take in the format as an argument, I think we need that argument for this to be useful.

**Comment by iceman1001** [comment]
interesting,
maybe add a line or two in the help text about you should use the command with either bin param or fc/cn/fmt params to make it extra clear.

**Comment by bettse** [comment]
> maybe add a line or two in the help text about you should use the command with either bin param or fc/cn/fmt params to make it extra clear.

Are there commands that have similar text that you'd like me to pattern off of?  Or if not, do you have a preference about if the comment precedes the examples or follows it?

**Comment by iceman1001** [comment]
Nothing particular in mind,  you would just add a newline character and add some more clear instructions,  about here
image

**Comment by iceman1001** [comment]
don't forget a line in CHANGELOG.md too

**Comment by iceman1001** [comment]
Thanks!

**Pull request merged**
