### PR TITLE
Update mfc_default_keys.dic

### PR DESCRIPTION
**Pull request by hamperfait**
Added Granada, ES transport Card keys

### CODE REVIEW

**Comment by iceman1001** [comment]
Excellent!

**Comment by iceman1001** [comment]
Is the key diversified or fixed?   Do you have a template of which keys goes to which sector/keytype?

**Comment by hamperfait** [comment]
I'm not sure what diversified/fixed keys are :/
I can, however, send the template of which key is for which sector.

**Comment by iceman1001** [comment]
Diversified keys = unique keys for each card in the system.
fixed = static keys for all cards in the system.
A template would be great.

**Comment by hamperfait** [comment]
I'm not sure whether they are diversified or fixed, sadly I have only one card to play with, but my guess would be fixed.
As for the template, would the output table of pm3 be what you are looking for?

**Comment by iceman1001** [comment]
Yes,  that would be excellent

**Comment by hamperfait** [comment]
Here you go. Sorry for the delay.

|---|-------------------|---|------------------|---| 
|sec| key A                 |res| key B                |res| 
|---|-------------------|---|------------------|---| 
|000|  0172066b2f03 | 1 |  000000270000 | 1 | 
|000|  385efa542907 | 1 |  70172066b2f0  | 1 | 
|000|  b385efa64290 | 1 |  0b0172066b2f  | 1 | 
|000|  0f385ffb6529  | 1 |  f0f0172066b2   | 1 | 
|000|  913385ffb752 | 1 |  2f130172066b  | 1 | 
|000|  29173860fc76 | 1 |  b2f170172066  | 1 | 
|000|  6291b3860fc8 | 1 |  6b2f1b017206 | 1 | 
|000|  87291f3861fc  | 1 |  66b2f1f01720  | 1 | 
|000|  c9739233861f | 1 |  066b2f230172 | 1 | 
|000|  fc9839273862 | 1 |  2066b2f27017 | 1 | 
|000|  2fca8492f386  | 1 |  72066b2f2b01 | 1 | 
|000|  63fca9492f38  | 1 |  172066b2f2f0  | 1 | 
|000|  863fcb959373 | 1 |  0172066b2f33 | 1 | 
|000|  3864fcba5937 | 1 |  70172066b2f3 | 1 | 
|000|  f3864fcca693  | 1 |  3b0172066b2f | 1 | 
|000|  3f3865fccb69  | 1 |  f3f0172066b2  | 1 | 
|---|------------------|---|------------------|---|

**Comment by iceman1001** [comment]
You think you can use your proxmark to simulate certain UIDs and see which keys the system is trying to use.

**Comment by hamperfait** [comment]
I'm afraid I can't... I don't live there anymore and I have no access to a reader

**Pull request merged**
