### PR TITLE
Some fixes for the reconnect feature

### PR DESCRIPTION
**Pull request by wh201906**
1. Add `msleep()` to reduce the CPU usage
2. Disable printing error information when calling `uart_open()` in `OpenProxmarkSilent()`

I'm still finding the reason of crash when running `hw connect` to a different port in the offline mode, so I created this as a draft.

### CODE REVIEW

**Comment by iceman1001** [comment]
different port means we can't auto reconnect.  it uses the "serial port"  that was used when first starting the client.
save in the global connection variable `g_conn`

**Comment by wh201906** [comment]
I know, but I thinks it should be possible to connect to a different port by running `hw connect` manually when the original connection is down

**Comment by iceman1001** [comment]
yes,  
   then we would need a way to break the reconnect thread.  ie detect if "pm3 is present and online"

**Comment by wh201906** [comment]
> yes, then we would need a way to break the reconnect thread. ie detect if "pm3 is present and online"

Yes. I'm working on this.

**Comment by wh201906** [comment]
Maybe we should merge this PR first, because the high CPU usage in reconnecting and the infinite `error: Could not connect` really bring a bad user experience, while the `hw connect` to different port is just a feature.

**Comment by iceman1001** [comment]
yes,  the sleep is needed.  

_merged_   :)

**Comment by iceman1001** [comment]
Something tells me the GENERIC build running on devices with no flash,  has the different serial port issue.

**Comment by wh201906** [comment]
> Something tells me the GENERIC build running on devices with no flash, has the different serial port issue.

Do you have the steps to reproduce it?

**Comment by iceman1001** [comment]
I suspect a non-flash enabled proxmark3 device,   will have different serial port enumeration when going from  normal operation - bootloader - flash - normal operation...

**Comment by wh201906** [comment]
Yeah I got the same bug on my EASY before. But I guess it won't happen from the normal operation -> unplug -> plug and reconnect

**Pull request merged**
