### PR TITLE
Fido fix

### PR DESCRIPTION
**Pull request by merlokk**

### CODE REVIEW

**Comment by doegox** [comment]
Thanks @merlokk 
The PR is merged in branch *future* as *master* is currently under freeze.
Branch *future* will be merged when @iceman1001 will be back.

**Comment by doegox** [comment]
https://github.com/RfidResearchGroup/proxmark3/tree/future

**Comment by iceman1001** [comment]
the default filename needs to match the file name template, where we denotate hf vs lf as prefix.   
Please revert that change.

**Comment by merlokk** [comment]
it will not work(
if i change the filename in the default folder and all the consts - will it ok?

**Pull request closed without merging**
