### PR TITLE
Fixes for ProxSpace v3.9

### PR DESCRIPTION
**Pull request by Gator96100**
I did move the file that is used to detect the ProxSpace version

### CODE REVIEW

**Comment by iceman1001** [comment]
and you forgot the readme.md ;)

**Comment by Gator96100** [comment]
I didn't, there is no v3.9 release yet.

**Comment by iceman1001** [comment]
No,  but your wording indicated it.  I must have misunderstood it
image

**Comment by Gator96100** [comment]
To be fair, there will be a v3.9 release today/tomorrow, I just want to test a few thinks before creating a new release.

**Pull request merged**
