### PR TITLE
Rick423n patch 1

### PR DESCRIPTION
**Pull request by rick423n**

### CODE REVIEW

**Comment by iceman1001** [comment]
Ok,   so what does this one do?   Besides build on MSBUILD?

1. microsoft/setup-msbuild@v1.0.2    isn't the last version.
2. no make clean,  make check,   and the other normal builds we do
    https://github.com/RfidResearchGroup/proxmark3/blob/master/.github/workflows/windows.yml

**Comment by iceman1001** [comment]
No to mention it fails...

**Comment by rick423n** [comment]
I don’t know what I’m doing still learning 😢

**Comment by iceman1001** [comment]
Why are you making a PR then?

**Pull request closed without merging**
