### PR TITLE
fix failed spi flash detection

### PR DESCRIPTION
**Pull request by ANTodorov**
fallback to 4 pages when SPI IC is unknown
some code styling
remove some unused code

### CODE REVIEW

**Comment by iceman1001** [comment]
Hm....
bootrom running spiffs when we need to get the ID out.  
If I remember it correct it was when you have an older bootrom and we flash a newer.    Have you tried that scenario?

**Comment by ANTodorov** [comment]
The flash ID is dedicated SPI request via Flash_UniqueID() (0x4B) https://github.com/RfidResearchGroup/proxmark3/blob/master/common_arm/flashmem.c#L516
The SPI is initialized, the UID is red via 0x4B and then stopped.
There is no spiffs or signature red via the bootloader - these functions are in the firmware context, not the bootloader.
Or we are talking about an old bootloader... Any hint how far back in the logs should I go to check?

**Comment by ANTodorov** [comment]
re-checked, there is no spiffs in the bootloader only the stuff to read the unique ID, used for the USB serial
image

**Comment by ANTodorov** [comment]
I think I am close to v2 - two global variables, one with the jedec identifier, the second one - a pointer to the spiFlashTable array
should I push the change to this PR or make a new one based on this?

This PR is just fixing a bug - out of bound index. here https://github.com/RfidResearchGroup/proxmark3/pull/2639/commits/68e354d7ef22eb260cd9f038ccfc1381546e55f3#diff-e8edff7301ceb63dec5c330434c2b1001aef706b32fab2120852f0170fd11996R468

the refactored code I am working at the moment is making things more clearer

**Comment by iceman1001** [comment]
Make a new PR

**Pull request merged**
