### PR TITLE
Added the autopwn read b key feature

### PR DESCRIPTION
**Pull request by matthiaskonrath**
As said before, I couldn't verify if this is working correct, so someone should please try it first.
(Well I made a little mistake with the pull requests / branches, now they are together... But the dictionary additions are small.)
@doegox and @iceman1001 nice work with the autopwn, now it looks really sexy ;)

### CODE REVIEW

**Comment by iceman1001** [comment]
Yup,  we are getting there.  have the function while making it better is a rapid way of development.
The readblock..  don't we have a method for it  /client/mifare/mifarehost.c ???

**Comment by doegox** [comment]
hmm it doesn't seem to run as expected, hold on...

**Comment by doegox** [comment]
my bad, for once your PR commits weren't in your master but in a branch (as it should) :)
yes it works, maybe add a log line for such keyB found as well?
```
[+] Found valid key: sector:   0 key type: B  key: xx xx xx...
```

**Comment by matthiaskonrath** [comment]
> my bad, for once your PR commits weren't in your master but in a branch (as it should) :)
> yes it works, maybe add a log line for such keyB found as well?
> 
> ```
> [+] Found valid key: sector:   0 key type: B  key: xx xx xx...
> ```

Yup I'll do that

**Comment by matthiaskonrath** [comment]
I originally thought that this would be handled by the print statement at the end ... well wrong loop.
But that should have fixed it :)

**Comment by iceman1001** [comment]
bleeding edge baby!   I know that this function is used tonight on a field test.  haha.

**Comment by matthiaskonrath** [comment]
> bleeding edge baby! I know that this function is used tonight on a field test. haha.

NICE ;)

**Comment by iceman1001** [comment]
Feels good, doesn't it?

**Comment by matthiaskonrath** [comment]
Yup, happy hunting ;)

**Pull request merged**
