### PR TITLE
T55xx save and restore (.bin, .eml)

### PR DESCRIPTION
**Pull request by mwalker33**
The files look ok from my side and the code looks correct., but I did have a little glitch with some conflicts that should have been resolved.
.
Please ensure it all looks ok from your side and lets work through any issues.

I have a  Can’t automatically merge, message, but not sure why.

Thanks

### CODE REVIEW

**Comment by mwalker33** [comment]
OK, found the conflict and corrected (in the change log), feel free to check and adjust as needed.

**Comment by doegox** [comment]
I'd also keep track of the lock bit of each page in the t55xx_memory_item_t struct.
Even if right now we don't deal with it, let's be prepared.

Hmm @mwalker33 working in your master branch is really messy, it's way easier if you create separate branch for PR and occasionally rebase your branch on the RRG master (and your master should just keep tracking RRG master, nothing else).
Try to think about it for next time.

I don't have time to solve it now but @iceman1001 beware that if I do a diff between current RRG master and proposed mwalker33/master I see more diffs than t55, e.g. all stuff related to Motorola & Verichip, not sure how it's a rollback or needed:

```diff
@@ -1313,7 +1297,6 @@ static command_t CommandTable[] = {
     {"nedap",       CmdLFNedap,         AlwaysAvailable, "{ Nedap RFIDs...             }"},
     {"nexwatch",    CmdLFNEXWATCH,      AlwaysAvailable, "{ NexWatch RFIDs...          }"},
     {"noralsy",     CmdLFNoralsy,       AlwaysAvailable, "{ Noralsy RFIDs...           }"},
-    {"motorola",    CmdLFMotorola,      AlwaysAvailable, "{ Motorola RFIDs...          }"},
     {"pac",         CmdLFPac,           AlwaysAvailable, "{ PAC/Stanley RFIDs...       }"},
     {"paradox",     CmdLFParadox,       AlwaysAvailable, "{ Paradox RFIDs...           }"},
     {"pcf7931",     CmdLFPCF7931,       AlwaysAvailable, "{ PCF7931 CHIPs...           }"},
@@ -1322,6 +1305,7 @@ static command_t CommandTable[] = {
     {"securakey",   CmdLFSecurakey,     AlwaysAvailable, "{ Securakey RFIDs...         }"},
     {"ti",          CmdLFTI,            AlwaysAvailable, "{ TI CHIPs...                }"},
     {"t55xx",       CmdLFT55XX,         AlwaysAvailable, "{ T55xx CHIPs...             }"},
+//    {"verichip",    CmdLFVerichip,      AlwaysAvailable, "{ VeriChip RFIDs...          }"},
     {"viking",      CmdLFViking,        AlwaysAvailable, "{ Viking RFIDs...            }"},
     {"visa2000",    CmdLFVisa2k,        AlwaysAvailable, "{ Visa2000 RFIDs...          }"},
     {"",            CmdHelp,            AlwaysAvailable, ""},
```
and all Motorola code being deleted.

**Comment by mwalker33** [comment]
mmm.  I have no idea about the motorola and other things I have never touched them ?
Happy to learn if I am doing something wrong.
My workflow has always been
1. Do a pull from the master into my fork (prior to making any changes)
2. Remove my local pc copy and re-clone from my fork
3. Work on the changes I want to make
4. When happy its should be ok, push back up to git.
5. Compare all changes reported by git are the intended changes (correct if needed)
6. Send Pull request (deal with anything reported)

This time, there was some conflicts that I needed to resolve (all in the T55 area.)

Happy do to what ever is needed.  Just need help as I find git very weird; and everything I have read keeps saying never to delete and re clone if you have made any pull requests.  Which I find weird as I can see how things can get out of sync.
Even the rebase howtos say not to do a rebase if you have may pull requests.... so I must be missing something.

Any help here welcome.

**Comment by doegox** [comment]
Motorola stuff: sorry my fault in trying to interpret the git tree, it was new commit on master after your PR. So it's ok to merge.
About the workflow: it gets easily "complicated" when you work on your master, see
Screenshot from 2019-10-12 23-52-47

The way I would recommend is:
* keep your master always in sync with the RRG master, never commit directly in your master, only git pull RRG on it to sync it. As right now it's desync, do a git merge of RRG master on your master once the PR is accepted, and things should be aligned again.
* to develop a feature, create a new branch, push it to your repo then make a PR of that branch to RRG master. If PR takes time, you can merge RRG master to your branch from time to time, possibly to solve conflicts. IMHO you can even git rebase your branch to RRG master while on PR. Nobody except possibly us have fetched your branch so you're not breaking the history of someone else and anyway the branch is meant to be temporary, see next point.
* when PR is accepted and merged to RRG master, you can simply delete your branch and git pull RRG on your master

I wasn't aware but apparently you can also give permission to us, RRG maintainers, to push commits on your PR branch, see https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork . This can be convenient if there is a little thing to fix, rather than explaining you what to fix and wait, we can just push directly the fix in the PR if we've that permission.

**Comment by doegox** [comment]
I pushed a fix because your code failed to build with my gcc8

**Comment by mwalker33** [comment]
Thanks, will setup. (almost what I was doing, but not the same and I can see the difference).
So, just to repeat in my words (and summary) to see if I have it right.
1. My master fork - only ever pull in changes from RRG (to keep it up to date)
2. Branch that to work on something.
3. Pull from the branch
4. Once the branch has been committed (or just needs cleaning), delete the branch and create a new one from my master.

Good to know that the motorola etc was an order thing as I was wondering why it did not show up when I was looking at the code differences as shown when setting up the pull request.

**Comment by mwalker33** [comment]
> I pushed a fix because your code failed to build with my gcc8

Do you remember what this was (so I can ensure I avoid it) ?

Thanks

**Comment by doegox** [comment]
yes I explained in the commit comments:

**Comment by doegox** [comment]
Actually I copy/pasted the text from "man sprintf" ;)
My compiler spotted it with this message:

`warning: passing argument 1 to restrict-qualified parameter aliases with argument 3`

**Comment by doegox** [comment]
> * My master fork - only ever pull in changes from RRG (to keep it up to date)

yes

> * Branch that to work on something.

yes

> * Pull from the branch

Not sure what you mean. Make a Pull Request out of that branch and we'll merge it in RRG master. If there is a discussion, you can still push more commits, merge changes from RRG master to keep it sync, even rebase it on RRG master if you prefer.

> * Once the branch has been committed (or just needs cleaning), delete the branch and create a new one from my master.

Once the branch has been merged into RRG master by us, you can delete it. If it needs cleaning, see previous step. Only if very messy and out of control, you might delete the branch, cancel the Pull Request, make a new one and a new Pull Request, but in principle this shouldn't be needed.

"create a new one" : well only for the next feature you want to propose and make a Pull Request out of it. With branches you can even submit several features in several Pull Requests at the same time, but they should all branch from the master, not be chained together. You can also keep a local "dev" branch for your own experiments if you want, play as much as you want with branches but refrain from committing directly to your master ;)

**Comment by mwalker33** [comment]
Thanks very much for you help and guidance.  Slowly getting my head around all the terms.

**Comment by doegox** [comment]
finally, I found the github doc about it: https://guides.github.com/introduction/flow/

**Pull request merged**
