### PR TITLE
Added the original VID and PID values

### PR DESCRIPTION
**Pull request by Gator96100**
Allow the pm3 script to find proxmarks with old firmware.

### CODE REVIEW

**Comment by iceman1001** [comment]
hm...  I thought the way was to add another where-object in the command...

**Comment by Gator96100** [comment]
That was what I originally planned, but white BT dongle it is separated as well.

**Comment by doegox** [comment]
white BT is separated because guarded by `if $FINDBTDONGLE` and much less mergeable in the Linux section.
Feel free to merge old and new VID/PID queries.

**Comment by Gator96100** [comment]
I didn't notice the `if $FINDBTDONGLE`, now it makes more sense. Anyway, the queries are merged.

**Comment by iceman1001** [comment]
Great!   Thanks @Gator96100 !

**Comment by iceman1001** [comment]
...dang..   in WSL it just hangs now....

**Comment by Gator96100** [comment]
Interesting, I did check the query in powershell. Didn’t test WSL though

**Pull request merged**
