### PR TITLE
Android platform adaptation.

### PR DESCRIPTION
**Pull request by xianglin1998**
I added some coding for Android platform.

### CODE REVIEW

**Comment by doegox** [comment]
thank you, please next time avoid mixing cosmetic changes and functional changes in the same commits. I merged manually the functional changes in master.
Please also translate Chinese comments.

**Comment by doegox** [comment]
and finally it will be easier for you if you work on a branch and PR the branch rather than working in your master

**Comment by doegox** [comment]
To be clear: this PR is closed but your changes are now merged in master

**Comment by doegox** [comment]
@xianglin1998  please check https://github.com/RfidResearchGroup/proxmark3/tree/android_lib
I made changes in master cmake deps to be able to use them from Android cmake.
I pushed in android_lib branch an attempt to use them but I cannot test it myself.
You can make a PR on top of android_lib if you need to tune things.
Thanks!

**Comment by doegox** [comment]
You might need to remove the "-std=c99" from the CMakeLists.txt

**Comment by xianglin1998** [comment]
ok, i will test.

**Comment by xianglin1998** [comment]
Wow, I tried to build with the new cmake script, and the build process was very smooth. The new cmake script is very concise and efficient, which is what I need to learn.   :)

**Comment by doegox** [comment]
so we can merge the android_lib branch ?

**Comment by xianglin1998** [comment]
I tried to translate some comments.

**Comment by xianglin1998** [comment]
if all done, we can tried merge the android_lib branch.

**Pull request closed without merging**
