### PR TITLE
Stack size fix in ldscript

### PR DESCRIPTION
**Pull request by sh7d**
It's just fixes my problems in #819

### CODE REVIEW

**Comment by iceman1001** [comment]
have you tested all functionality so nothing else breaks?

**Comment by sh7d** [comment]
Well, hitag works, mf autopwn works, mf sim works, i dont have time for more

**Comment by doegox** [comment]
@iceman1001 there last days we pushed the cursor back & forth a few times depending on the bugs, sometimes with bugfixes which relax constraints but we should track all use cases that claim a larger or a smaller stack, see which ones need to be fixed and know what are the real min/max where nothing breaks (if. there is such fine spot today :) )
Honestly I'm lost at this point.

**Comment by doegox** [comment]
and poking @slurdge who opened the Pandora box ;)

**Comment by slurdge** [comment]
Hey this is me, the pandora box opener!
What is happening is that we have two types of workloads: workloads that put everything on the stack (which is good), and workloads that use most of bigbuf (hopefully with a little bit of stack).

I guess that by chance 40K bigbuf was the sweet spot, what we can do is go back to 40K bigbuf, mark the end of it, and compute what was the max stack at that point.

However, moving forward we should:
 - Have less & less static buffers. Either alloc() them or stack them;
 - Be able to change the stack size depending on the workloads, either in the Makefile (with rules for Standalones etc.) or at the runtime (more difficult)

**Comment by doegox** [comment]
> I guess that by chance 40K bigbuf was the sweet spot, what we can do is go back to 40K bigbuf, mark the end of it, and compute what was the max stack at that point.

Well that was the status with 40K BigBuff + 8488 stack wasn't it ? And for mysterious reasons it's buggy (#819)

**Comment by slurdge** [comment]
Yeah it should... But that's why I suggested to go back. However I know remember some other fine point: we don't control that BigBuf is at the end.
So, what probably happens.
Before
```Code | BigBuf | Some other .bss content | Stack [Filling space]```
If "some other content" is not used with heavy stack usage, then everything is "fine".
Now
```Code | .bss | BigBuf Filling space | Stack [Fixed Size]```
So _by design_ BigBuf is at the end. We should check how much .bss there is.

**Comment by iceman1001** [comment]
Right now its the bigbuff usage all cross the device side code which leads to weird stuff.
Sometimes it check available tracelen limit and some time there is a hard encoded 40000 size.  
We need to go through all of the code find all culprits.   Nothing else to do.

**Comment by slurdge** [comment]
This man speaks the gospel.
BTW the .bss size is ~6.4K on latest trunk. So it is quite possible that the aforementioned scenario is taking place

**Comment by iceman1001** [comment]
Closing since this one isn't a prefereed solution to the actual problem.

**Pull request closed without merging**
