### PR TITLE
WIP Travis tests, do not merge!!

### PR DESCRIPTION
**Pull request by doegox**
branch just for testing Travis OSX <> Python3 issue in a hopefully faster setup
feel free to add commits to this branch and see how Travis behaves

### CODE REVIEW

**Comment by doegox** [comment]
https://travis-ci.org/RfidResearchGroup/proxmark3/builds/653542824
test passed, wtf, I'm going mad

**Comment by doegox** [comment]
https://travis-ci.org/RfidResearchGroup/proxmark3/builds/653591253succeeded too, what's going on ??

**Comment by doegox** [comment]
seems latest test worked fine, now deploying it on master...
https://travis-ci.org/RfidResearchGroup/proxmark3/jobs/653624531

**Comment by doegox** [comment]
fix ported to master, passed

**Comment by iceman1001** [comment]
@sigwinch28  Don't forget a line in the CHANGELOG.md...  
same goes for you @doegox   :)

**Pull request closed without merging**
