### PR TITLE
Update mfc_default_keys.dic

### PR DESCRIPTION
**Pull request by CountParadox**
added keys to my apartment building

### CODE REVIEW

**Comment by iceman1001** [comment]
You know if they are static keys?   I.e. same keys on all cards in the apartment building?

**Comment by TomHarkness** [comment]
In Aus this is usually the case. Never seen a building where the keys differ.

**Comment by iceman1001** [comment]
Ping,  
can you verify that this PR contains static keys across several cards from the same system?

**Comment by CountParadox** [comment]
Yes; I tested another card and many of these keys also unlocked them. (The remaining were found in default dictionary)

**Comment by iceman1001** [comment]
ok,  many is good indicator,  but it also begs the question,  which keys doesn't exists om multiple cards from same system?

**Pull request merged**
