### PR TITLE
HF_COLIN 2/3 : Now able to read Known  key schemes from SPIFFS JSON Config File

### PR DESCRIPTION
**Pull request by cjbrigato**
BEWARE : add device-side json parsing and overlapping string/standard libc functions.
 Edit : usable and quite working. 
It works, but it's messy and heavy.

Needs ton of cleaning but I needed to be sure to be able to merge before any breaking change from master.
Next step is to read ARRAY of Known schemes in Config file dynamically then Clean all the mess.

### CODE REVIEW

**Comment by cjbrigato** [comment]
Here we are, it now lacks a lot a of cleaning but it works just as expected.
HF_COLIN standalone is now fed by "hf_colin/schemas.json" file with an array of MF1KCShemas as json :) yiha

**Comment by iceman1001** [comment]
Great!

That json file  do you need to compile it in? or can you upload it to device and standalone mode finds it?

**Comment by cjbrigato** [comment]
You upload it. It's dynamic. Hf_colin/schemas.json in spiffs

**Comment by cjbrigato** [comment]
copy this in `schemas.json` 
```
[
   {
      "name":"UrmetCaptive",
      "trigger":"0x8829da9daf76",
      "keysA":[
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76"
      ],
      "keysB":[
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76",
         "0x8829da9daf76"
      ]
   },
   {
      "name":"Noralsy",
      "trigger":"0x414c41524f4e",
      "keysA":[
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e",
         "0x414c41524f4e"
      ],
      "keysB":[
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e",
         "0x424c41524f4e"
      ]
   },
   {
      "name":"Infineon/Hexact",
      "trigger":"0x484558414354",
      "keysA":[
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354",
         "0x484558414354"
      ],
      "keysB":[
         "0xa22ae129c013",
         "0x49fae4e3849f",
         "0x38fcf33072e0",
         "0x8ad5517b4b18",
         "0x509359f131b1",
         "0x6c78928e1317",
         "0xaa0720018738",
         "0xa6cac2886412",
         "0x62d0c424ed8e",
         "0xe64a986a5d94",
         "0x8fa1d601d0a2",
         "0x89347350bd36",
         "0x66d2b7dc39ef",
         "0x6bc1e1ae547d",
         "0x22729a9bd40f"
      ]
   }
]
```
then
`mem spiffs load f schemas.json o hf_colin/schemas.json`

tada.

**Comment by cjbrigato** [comment]
> Great!
> 
> That json file do you need to compile it in? or can you upload it to device and standalone mode finds it?

if you read the Third commit I guess the "Dynamically loaded at runtime" should have been a hint ? :p

**Comment by cjbrigato** [comment]
@doegox / @iceman1001 / @slurdge , any news ? Waiting for something, or just did not have the time ?

**Comment by iceman1001** [comment]
Oj,  you want to merge it?   I thought it was WIP?    Sure,  lets merge

**Comment by cjbrigato** [comment]
no it's not a wip thx to last commit.
it just need a little cleaning and something could be done better regarding "nprintf.c" and some implementation that overlap built-ins. But it's ok i prefer it being tested as is before cleaning for nothing ;)
Coherence pass will be done, still my hf has never been lighter, no matter the json_parser integration (Here I deeply want to thanks BigBuf_malloc to be such a wonderful dropin replacement for malloc).

**Comment by iceman1001** [comment]
@cjbrigato   Go go go!

**Pull request merged**
