### PR TITLE
Improve user experience

### PR DESCRIPTION
**Pull request by AxisRay**
Improve user experience
Before:
image
After:
image

### CODE REVIEW

**Comment by iceman1001** [comment]
Interesting find...

**Comment by doegox** [comment]
Good catch but the solution sounds overcomplicated.
It seems this simple patch has the same effect.
```diff
diff --git a/client/src/proxmark3.c b/client/src/proxmark3.c
index d1507923a..d1f74bcba 100644
--- a/client/src/proxmark3.c
+++ b/client/src/proxmark3.c
@@ -135,7 +135,7 @@ static int check_comm(void) {
         char prompt_filtered[PROXPROMPT_MAX_SIZE] = {0};
         memcpy_filter_ansi(prompt_filtered, prompt, sizeof(prompt_filtered), !session.supports_colors);
         rl_set_prompt(prompt_filtered);
-        rl_forced_update_display();
+        rl_redisplay();
 #endif
         CloseProxmark(session.current_device);
     }
```
Do you confirm @AxisRay or did I miss sth ?

**Comment by AxisRay** [comment]
Confirmed!
It seems that no different.
image

**Comment by doegox** [comment]
thank you

**Pull request merged**
