### PR TITLE
Fix broken 'lf em 4x70 brute' command

### PR DESCRIPTION
**Pull request by adite**
Unfortunately, a stupid mistake has crept in - the sizeof() a pointer instead an array was taken.
Sorry for that...
This pr fixes it and also enhance the timeout of the brute command to 1h.
This is because it can take about 45 minutes at worst case.

Regards,
Adrian

### CODE REVIEW

**Comment by iceman1001** [comment]
Nasty little bug...

**Comment by adite** [comment]
Not ideal for my first contribution to this project...

**Comment by henrygab** [comment]
It's a common mistake.  The ARRAYSIZE() macros are **_inherently_** unsafe in C.   As bugs go, that's one that hits even the most experienced coders.  (I have a longer diatribe against that macro... but I'll spare you). 

Good news -- I confirmed with this fix that this cleanly found the partial for block 9.   Well done!

**Comment by henrygab** [comment]
And now confirmed for block 8.  Seems like a solid implementation of that algorithm!

**Pull request merged**
