### PR TITLE
Descriptive Names for Lua Scripts

### PR DESCRIPTION
**Pull request by msoose**
#890

Rename Lua scripts to try to be a bit more standardized and descriptive.

Most scripts try to follow `frequency_cardtype_function` and some include a `-modifier` which might be necessary to delineate between similar scripts that require specific functions, card types, or other things a user should be aware of.

`data_function` is for local data manipulation tasks that don't necessarily require actually interfacing with a card to modify data.

### CODE REVIEW

**Comment by iceman1001** [comment]
alright,  there is a conflict that needs to be resolved,   and then we merge it,
next step would be moving files into sub folders,  "hf"  or "lf"  to make it even cleaner

**Comment by msoose** [comment]
Hm, seems I deleted my forked repo with the branch for these changes. Sigh.

**Comment by doegox** [comment]
> Hm, seems I deleted my forked repo with the branch for these changes. Sigh.

oops.
I could recover your commits thanks to the GitHub CLI (https://github.com/cli/cli/blob/trunk/docs/install_linux.md).
I rebased it and pushed it in a branch: https://github.com/RfidResearchGroup/proxmark3/tree/lua-script-rename
So I'll close this one, we can still discuss here or when other changes are proposed, just open another PR against that branch.

**Comment by doegox** [comment]
@iceman1001 what's the conflict you were talking about ?

**Comment by iceman1001** [comment]
There were conflicts but now they seem to be gone.  Maybe because the issue is closed?
I didn't look at what the conflicts was about.

**Comment by doegox** [comment]
Hmm I had no conflict when I rebased them to master. Anyway, all good now

**Comment by doegox** [comment]
now merged in master

**Comment by iceman1001** [comment]
@msoose    the  /doc may need some love with updated filename ...

**Comment by doegox** [comment]
@msoose here is a list of things to adapt from old to new script names:
```
armsrc/Standalone/hf_aveful.c
190:                    // We're skipping 14 blocks (56 bytes) here, as that "[...] has version/signature/counter data here" according to comments on dumptoemul-mfu

client/src/cmdhfmfu.c
139:    PrintAndLogEx(NORMAL, "Hint: See " _YELLOW_("`script run dumptoemul-mfu`") " to convert the .bin to the eml");

client/src/scripting.c
58: * Enable / Disable fast push mode for lua scripts like mfckeys

doc/cheatsheet.md
236:pm3 --> script run dumptoemul -i dumpdata.bin
288:pm3 --> script run dumptoemul -i dumpdata.bin
308:pm3 --> script run dumptoemul-mfu -i hf-mfu-XXXX-dump.bin -o hf-mfu-XXXX-dump.eml
315:pm3 --> script run hf_bruteforce -s 0x11223344 -e 0x11223346 -t 1000 -x mfc
320:pm3 --> script run hf_bruteforce -s 0x11223344556677 -e 0x11223344556679 -t 1000 -x mfu
566:pm3 --> script run dumptoemul -i xxxxxxxxxxxxxx.bin
576:pm3 --> script run emul2dump -i myfile.eml -o myfile.bin
588:pm3 --> script run formatMifare -k FFFFFFFFFFFF -n FFFFFFFFFFFF -x

doc/magic_cards_notes.md
198:script run remagic
521:script run ul_uid -h
528:script run remagic -u
726:script run mfu_magic -h

client/luascripts/lf_t55xx_writetest.lua
38:script run test_t55x7 [-h] [-t <modulation type>

client/luascripts/hf_mf_magicrevive.lua
22:    -u      remagic a Ultralight tag w 7 bytes UID.
=> try to revive a bricked magic Ultralight tag w 7 bytes UID.

client/luascripts/data_readpwdmem.lua
12:You should now use read_pwd_mem_spiffs instead after the updated BogRun standalone mode.
252:    Dbprintf("- [  !  ] -> use 'script run read_pwd_mem_spiffs' to print passwords");

client/luascripts/data_example_parameters.lua
7:usage = 'script run parameters.lua -a 1 -blala -c -de'
55:    script run parameters.lua -a 1 -blala -c -de

client/luascripts/hf_ntag-3d.lua
224:    -- Set the arguments for mfu_magic script v1.0.8
230:    require('mfu_magic')

client/luascripts/hf_mf_keycheck.lua
63:        print("Timeout while waiting for response. Increase TIMEOUT in mfckeys.lua to wait longer")
240:    print('[+] mfckeys - Checkkey execution time: '..os.difftime(end_time, start_time)..' sec')

client/luascripts/hf_mf_dump-laundromat.lua
3:-- Just copy luxeodump.lua to client/luascripts/
4:-- and run "script run luxeodump"

client/luascripts/hf_lf_multi_bruteforce.lua
29:    -- I dont know LUA, so I used Brian Redbeards lf_bulk_program.lua script as a starting point, sorry if its kludgy.
113:-- The code below was blatantly stolen from Brian Redbeard's lf_bulk_program.lua script

client/luascripts/lf_hid_bulkclone.lua
2:-- lf_bulk.lua - A tool to clone a large number of tags at once.

client/luascripts/hf_mfc_uidbruteforce.lua
1:-- Run me like this (connected via USB): ./pm3 -l hf_bruteforce.lua
2:-- Run me like this (connected via Blueshark addon): ./client/proxmark3 /dev/rfcomm0 -l ./hf_bruteforce.lua

client/luascripts/hf_mf_autopwn.lua
131:        -- Set the arguments for htmldump script
134:        require('htmldump')
```

**Comment by msoose** [comment]
If moving to hf/ and lf/ subdirectories, should scripts still be prefixed by hf_ and lf_?

Is there really a need to update comments in source?

**Comment by doegox** [comment]
We're no totally ready for subdirs.

* [x] list subdirs in `script list`
* [x] `script run subdir/script` runs
* [ ] `script run script` doesn't work, need to recurse in subdirs when we search automatically in all script dirs

> If moving to hf/ and lf/ subdirectories, should scripts still be prefixed by hf_ and lf_?

No. The advantage I see with subdirs is that when you know the script you can type its short form and it will run: `script run aztek` will run `hf_14a/aztek.lua`

Note that about tabs, it only works when you specify a full path anyway: `script run client/luascripts/hf<tab>`

I've still several changes I want to do in the renaming but for now, please just adjust the current names as per the list I made, including in comments.

**Comment by doegox** [comment]
renaming done

**Pull request closed without merging**
