### PR TITLE
BogRun bug fix + helper lua script

### PR DESCRIPTION
**Pull request by bogiton**

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice one!,   it seems you didn't pull latest before you did your PR...   Would you mind solving that merge conflict?

**Comment by bogiton** [comment]
Was there a merge conflict? When I PR yesterday, all checks were green.

**Comment by RfidResearchGroup** [comment]
I think I resolved it.  Pull and see if it compiles (well with your mode in armsrc/Makefile  )   and test it out... I took some neat led shows from @cjbrigato  :)

**Comment by cjbrigato** [comment]
Haha now I'm I'm haste  to provide next cjbrun commit : since it permit to deal with 4 dumps  in circular way, I had very hard time designing clever  workflow to handle a 4-levels deep menu with one button and 4 LEDs... stay tuned :p

**Comment by RfidResearchGroup** [comment]
the led show is really nice!

**Pull request merged**
