### PR TITLE
Update bignum.c

### PR DESCRIPTION
**Pull request by sun1ch**
Delete unused variable t = 0

Signed-off-by: Alex <98668583+sun1ch@users.noreply.github.com>

### CODE REVIEW

**Comment by iceman1001** [comment]
its a bit unclear this one.
Since the mbedtls uses ASM code in macros direct after the definition of variable t.  

`MULADDC_INIT`    etc..

And I am not sure at all if the ASM code actually fills the memory or uses the memory for this variable t.

**Comment by sun1ch** [comment]
There's an error appears with variable t = 0  in bignum.c

**Comment by sun1ch** [comment]
Without t = 0 in 1442 string and t++ in 1448 client compiled without error

**Comment by iceman1001** [comment]
yes,   I understand that there is an warning in GCC 12,   but your fix doesn't verify if removal of the variable t, isnt used in the mbedtls macros.

**Comment by iceman1001** [comment]
closing because of inactivity from poster

**Pull request closed without merging**
