### PR TITLE
Bug Fix : T55x7 timings save to flash

### PR DESCRIPTION
**Pull request by mwalker33**
This should now support the old flash saved settings for the t55x7 timings.  then allow the new ones to be added as needed.

### CODE REVIEW

**Comment by mwalker33** [comment]
Hold on this till I get back.  I will change the z option from "erase" to set defaults in the client (as suggested).  and Auto set back to the pm3 if "FF"

**Comment by mwalker33** [comment]
Ok, should be good to go when your ready.
Thanks

**Comment by doegox** [comment]
thanks !

**Comment by iceman1001** [comment]
Excellent!

**Pull request merged**
