### PR TITLE
Update mfc_default_keys.dic With more keys

### PR DESCRIPTION
**Pull request by PommyGit**
Just added a bunch of keys to the dictionary

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice,

Before any merging we need to sort out if these keys are confirmed static default keys.   Ie:  are these keys to be the same on multiple cards from the same system,    or are they unique on each card.

And from which system do these keys come from?

**Comment by PommyGit** [comment]
These keys are from the Transperth Smartrider system. I generally always have zero success when using hf mf autopwn on such cards but since i started gathering the list using hf mf autopwn -f ./my-key-collection.dic is alwasys a resounding success. I hope that answers your question

**Comment by iceman1001** [comment]
Good,  Lets see what metrodroid project says,    https://github.com/metrodroid/metrodroid/wiki/SmartRider#key-diversification

They concluded that there are some static keys and some diversified.

Now which ones in your list fits their blocks for static keys?   Since those we want in the default key list,

**Comment by iceman1001** [comment]
You also have lots of duplicates in your keys.  That needs to be addressed too.

**Comment by PommyGit** [comment]
Strange how I unique this in bash and this was the output. Sorry for the sloppiness. I'm AFK at the Mo but will address these issues asap including the link to the static keys that @iceman1001  posted.  Sorry guys.

**Comment by iceman1001** [comment]
I will close this one,   since I pushed @s00se  PR and his post of unique keys here.

@PommyGit  you can verify that short list of keys against the link and make a new PR if needed.

Thanks!

**Comment by iceman1001** [comment]
and no... that wasn't unique..  I removed the duplicates...

**Pull request closed without merging**
