### PR TITLE
add pac trace file

### PR DESCRIPTION
**Pull request by danshuk**

### CODE REVIEW

**Comment by iceman1001** [comment]
Awesome!  Thanks bro!

**Comment by iceman1001** [comment]
and... now that I merged it,  I remember,  you will need to add a line in /traces/README.txt aswell.
Trying to keep documentation on top of things.

**Comment by iceman1001** [comment]
and maybe implement the  `lf pac sim`  ??

**Comment by danshuk** [comment]
Sure, I'll update the readme now. I plan to implement the sim, but that needs some deeper thought.. I need to read more closely lfops.c etc. as maybe I need to implement nrz waveform generation, unless I missed something...

**Comment by iceman1001** [comment]
Don't think you need to do much.  Search the other cmdlf* files for a lf system with nrz and look into sim ask.

**Pull request merged**
