### PR TITLE
Now it's working both with WIN and UNX

### PR DESCRIPTION
**Pull request by Windslab**
Seems something went wrong to `mfc_gen3_writer` branch. A lot of conflicts.

### CODE REVIEW

**Comment by Windslab** [comment]
@doegox Will add? Please remove the old branch.

**Comment by doegox** [comment]
I've rebased the branch to the current master.
I wanted to merge your PR to it but it seems your git is not properly configured, your name and email are shown as
`Winds <Yev@DESKTOP-143DRNI.(none)>`
Please configure it with a proper email.

**Comment by Windslab** [comment]
> I've rebased the branch to the current master.
> I wanted to merge your PR to it but it seems your git is not properly configured, your name and email are shown as
> `Winds <Yev@DESKTOP-143DRNI.(none)>`
> Please configure it with a proper email.


Yeah okay I'll check! Could you a file add it by hand?

**Comment by doegox** [comment]
yes I can do it, I just need you to tell me a proper email

**Comment by Windslab** [comment]
> yes I can do it, I just need you to tell me a proper email

lalamy@yandex.ru

Many Thanks

**Comment by doegox** [comment]
it's merged in https://github.com/RfidResearchGroup/proxmark3/tree/mfc_gen3_writer which has been rebased on latest master

**Comment by Windslab** [comment]
> it's merged in https://github.com/RfidResearchGroup/proxmark3/tree/mfc_gen3_writer which has been rebased on latest master

@doegox That's grait! But could you merge it to the Master? Why are you using `mfc_gen3_writer ` branch?

**Comment by doegox** [comment]
Because if I remember well there were several issues documented in the begin of the script to fix first.
poking @iceman1001

**Comment by Windslab** [comment]
> Because if I remember well there were several issues documented in the begin of the script to fix first.
> poking @iceman1001

No! The main reason why you did the `mfc_gen3_writer ` brach was a non workable script on Linux. Remember? It was can't found any en *eml files. In the script begen wish list writen by me and added by @iceman1001

You can try:
1. Do a dump of your goal card whith you wanna copy.
2. Put a new blank card
3. Run script/with UID changing(for gen3) and choice dump with you gonna write.

Also you can erease and reformat AC's.

Ofcourse small trubles can be, you can fix it by hands. And I also will be happy to erase all problems.
@iceman1001 did a code corection, now it's perfetc.

Now it's totally working on Windows and Linux. No problem. I haven't oportunity to chack on MacOS but it's FreeBSD, must also works.

**Comment by doegox** [comment]
ok, I don't know Lua scripts so I'll let @iceman1001 do the merge.

**Pull request closed without merging**
