### PR TITLE
hf iclass view, permute - now use cliparser

### PR DESCRIPTION
**Pull request by tcprst**
Hopefully partial conversions like this are okay.  Not sure how much time I'll have this week to work on this.

### CODE REVIEW

**Comment by doegox** [comment]
Yes partial are ok but please chase all occurrences.
E.g.
```
doc/cheatsheet.md
51:pm3 --> hf iclass permute r 3F90EBF0910F7B6F
armsrc/Standalone/hf_iceclass.c
128:            DbpString("2. " _YELLOW_("hf iclass view f " HF_ICLASS_FULLSIM_MOD_BIN));
```

**Comment by iceman1001** [comment]
For these commands I suggest also adding the short option
```
hf iclass view -s -e
hf iclass permute -r
```

**Comment by tcprst** [comment]
@doegox My apologies, I was originally planning to do that when I completed the whole `hf iclass` section before submitting a PR, I'll now do it inline with each command so I don't miss anything.

@iceman1001 I've added the short options, I just figured we might use `-e` `-r` `-s` elsewhere and wanted to "reserve" them so they would be consistent across all commands.

**Comment by iceman1001** [comment]
great,
but a conflict in commands...
did you pull first?

**Comment by tcprst** [comment]
My apologies for this mess, I'm still learning PRs.

**Comment by iceman1001** [comment]
hm.. that commands.md,  looks like your changed the sorting order..

And no problem,  learning dealing with a PR isn't easy

**Comment by tcprst** [comment]
Yeah, I believe @doegox changed it in master which led to the merge conflict.  My latest commit matches his order with my change if you go look at the net diff of the commits in the "Files Changed" tab you should see: 
Screen Shot 2020-10-06 at 11 05 44 AM

**Comment by doegox** [comment]
FYI Commands.md is supposed to be auto-generated with `proxmark3 -m`, so in case of conflict, simply regenerate it.
I'm pushing it to `make style` so hopefully it'll be more often updated.

**Comment by doegox** [comment]
Done: https://github.com/RfidResearchGroup/proxmark3/commit/cb20d9344890e64e9a4d197291074aad56945d05

**Pull request merged**
