### PR TITLE
SPIFFS: implement dumping from SPIFFS to client trace buffer

### PR DESCRIPTION
**Pull request by hazardousvoltage**
Sometimes one has a bunch of traces in SPIFFS after a long day of standalone work, and wants to look at them and decide what to save.  Adds '-t' option to mem spiffs dump, to download the data into client trace buffer instead of creating a local file which one must then 'trace load'

Not sure I like how I implemented this, or whether it's useful to anyone else.

### CODE REVIEW

**Comment by iceman1001** [comment]
Cool,

Only thing I see is that -t vs -s  is excluding,    when you can use "-t"  and "-s" at the same time.   Save and load graphbuff.

Just check if there was slen and run that part of the code too.

**Comment by hazardousvoltage** [comment]
Hi, thanks for the comments..

-t does not exclude -s, it's excluding -d

Perhaps better, if -t is used, dump only to tracebuffer, but if used with -d, also save to file?

**Comment by iceman1001** [comment]
yeah,   

so to make it perfectly clear how it should work, 

-t  fill trace
-d  save to file

if both params,   do both.  Meaning we can both save to file and load trace.
if only one,  it does what that param intends.

**Comment by iceman1001** [comment]
Ignore my comments,      this way works well.

Thanks!

**Pull request merged**
