### PR TITLE
hf topaz - now use cliparser

### PR DESCRIPTION
**Pull request by tcprst**
Topaz commands now use cliparser

### CODE REVIEW

**Comment by iceman1001** [comment]
... now you need to resolve the cliparser_todo...

**Comment by tcprst** [comment]
> ... now you need to resolve the cliparser_todo...

it's resolved, right?

**Comment by tcprst** [comment]
> > ... now you need to resolve the cliparser_todo...
> 
> it's resolved, right?

nevermind, I see the conflict

**Comment by iceman1001** [comment]
👍

**Pull request merged**
