### PR TITLE
Connection fix on msys2 win32

### LINKED ISSUE #188: Proxmark client stuck at "[=] Communicating with PM3 over USB-CDC" for 10-15 minutes
**Describe the bug**
After updating ProxSpace and Proxmark 3 RDV4 to latest versions/fw it takes 10-15 minutes for the client to load completely. It gets stuck at "Communicating with PM3 over USB-CDC". 

After waiting 10-15 minutes, it finally loads as usual (pm3 prompt).  Unplugging and/or trying different USB port does not help...

Console output:
`pm3 ~/client$ ./proxmark3.exe com7

======. ===.   ===. ====.     ...iceman fork
==...==.====. ====.   ..=.      ...dedicated to RDV40
======..==.====.==. ====..
==..... ==..==..==.   ..=.    iceman@icesql.net
==.     ==. ... ==. ====..   https://github.com/rfidresearchgroup/proxmark3/
...     ...     ... .....  pre-release v4.0

Support iceman on patreon,   https://www.patreon.com/iceman1001/

[=] Using UART port com7
**[=] Communicating with PM3 over USB-CDC``**

**To Reproduce**
1.  Start ProxSpace v3.0 x64 (updated today to latest Git)
2.  Start Proxmark client (from this repo)
3. Gets stuck

**Expected behavior**
I´m expecting the client to load immediately

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

 - hw version

[ Proxmark3 RFID instrument ]

 [ CLIENT ]
  client: RRG/Iceman

 [ PROXMARK RDV4 ]
  external flash:                  present
  smartcard reader:                present

 [ PROXMARK RDV4 Extras ]
  FPC USART for BT add-on support: absent

 [ ARM ]
 bootrom: RRG/Iceman// 2019-05-10 09:11:16
      os: RRG/Iceman// 2019-05-10 09:11:44

 [ FPGA ]
 LF image built for 2s30vq100 on 2019/ 4/18 at  9:35:32
 HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev B
  --= Embedded Processor: ARM7TDMI
  --= Nonvolatile Program Memory Size: 512K bytes, Used: 249999 bytes (48%) Free: 274289 bytes (52%)
  --= Second Nonvolatile Program Memory Size: None
  --= Internal SRAM Size: 64K bytes
  --= Architecture Identifier: AT91SAM7Sxx Series
  --= Nonvolatile Program Memory Type: Embedded Flash Memory

 - hw status

#db# Memory
#db#   BIGBUF_SIZE.............40000
#db#   Available memory........40000
#db# Tracing
#db#   tracing ................1
#db#   traceLen ...............0
#db# Currently loaded FPGA image
#db#   mode.................... HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23
#db# Flash memory
#db#   Baudrate................24MHz
#db#   Init....................OK
#db#   Memory size.............2 mbits / 256kb
#db#   Unique ID...............0xd567a882a7a67f26
#db# Smart card module (ISO 7816)
#db#   version.................v3.11
#db# LF Sampling config
#db#   [q] divisor.............95 (125 kHz)
#db#   [b] bps.................8
#db#   [d] decimation..........1
#db#   [a] averaging...........Yes
#db#   [t] trigger threshold...0
#db# LF T55XX config
#db#   [a] startgap............29*8 (232)
#db#   [b] writegap............17*8 (136)
#db#   [c] write_0.............15*8 (120)
#db#   [d] write_1.............47*8 (376)
#db#   [e] readgap.............15*8 (120)
#db# Transfer Speed
#db#   Sending packets to client...
#db#   Time elapsed............500ms
#db#   Bytes transferred.......273920
#db#   Transfer Speed PM3 -> Client = 547840  bytes/s
#db# Various
#db#   MF_DBGLEVEL.............1
#db#   ToSendMax...............-1
#db#   ToSendBit...............0
#db#   ToSend BUFFERSIZE.......2308
#db# Installed StandAlone Mode
#db#    LF HID26 standalone - aka SamyRun (Samy Kamkar)

 - data tune
[=] Measuring antenna characteristics, please wait...

...

[+] LF antenna: 29.60 V - 125.00 kHz
[+] LF antenna: 47.16 V - 134.00 kHz
[+] LF optimal: 58.92 V - 139.53 kHz
[+] LF antenna is OK

[+] HF antenna: 17.63 V - 13.56 MHz
[+] HF antenna is OK

[+] Displaying LF tuning graph. Divisor 89 is 134khz, 95 is 125khz.

### PR DESCRIPTION
**Pull request by merlokk**
it for fix #188

### CODE REVIEW

**Comment by merlokk** [comment]
all the magic happens here
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/comms.c#L347-L350

if i do this:
```
//        pthread_mutex_lock(&spMutex);

        res = uart_receive(sp, (uint8_t *)&rx_raw.pre, sizeof(PacketResponseNGPreamble), &rxlen);
pthread_mutex_lock(&spMutex);
```
all works

**Comment by merlokk** [comment]
and if i do this:

```
//        pthread_mutex_lock(&spMutex);
sleep(1);
        res = uart_receive(sp, (uint8_t *)&rx_raw.pre, sizeof(PacketResponseNGPreamble), &rxlen);
pthread_mutex_lock(&spMutex);
```

it can't communicate with pm3

looks like some races

**Comment by merlokk** [comment]
added this
`PrintAndLogEx(ERR, "*%d", pthread_self());` and i see that only one thread calls this code...

**Comment by merlokk** [comment]
and added
```
PrintAndLogEx(ERR, ">%d", pthread_self());
                if (pthread_mutex_trylock(&spMutex) != 0)
                    PrintAndLogEx(ERR, "mutex can't locked!");
```
and i see - it called from different thread

so maybe `uart_receive` calls `TestProxmark` somewhere?

**Comment by merlokk** [comment]
I dont see any useful code in `uart_reconfigure_timeouts` it allready calls by `uart_open`
it looks this code can just easily deleted...

**Comment by iceman1001** [comment]
Just because you don't see it, doesn't mean it is useless.  

The Uart_reconfigure_timeouts() is needed to reset the timeouts before we reconnect to a comport.

**Comment by merlokk** [comment]
and something strange here
```
    // try to open USB connection to Proxmark
    if (port != NULL) {
        OpenProxmark(port, waitCOMPort, 20, false, speed);
    }
sleep(500);
    if (session.pm3_present && (TestProxmark() != PM3_SUCCESS)) {
        PrintAndLogEx(ERR, _RED_("ERROR:") "cannot communicate with the Proxmark\n");
        CloseProxmark();
    }

```

it from proxmark.c:489

this sleep hangs the proxmark client...

**Comment by merlokk** [comment]
ok, as for sleep i was wrong...   it in seconds...
but it not helps

**Comment by doegox** [comment]
Hmm I had a look.
If I uncomment the mutex in TrestProxmark as suggested by @merlokk I get the same "deadlock" problem.
It's not a real deadlock, it's a problem of the default SCHED_OTHER that always favor the comm thread as it's almost always locking spMutex in its loop. I thought locked threads were fairly queued but that's not how it works.
Here is an example where the "deadlock" lasted only a fraction of second  but we see comm thread was given the spMutex 15 times before TestProxmark could get it:
```
>1553577728 LOCKING1
> LOCKED1
>1553591616 LOCKING3             <=
> UNLOCKED1

>1553577728 LOCKING1
> LOCKED1
> UNLOCKED1
>1553577728 LOCKING1
> LOCKED1
> UNLOCKED1

Repeating 13 more times, then:

> LOCKED3                      <=
> UNLOCKED3
>1553577728 LOCKING1
> LOCKED1
> UNLOCKED1
```

One option could be to change towards the SCHED_RR but apparently now this requires some "nice" capabilities, a bit overkill.

I tries calling `pthread_yield` to release the comm thread but that didn't help.

What worked for me was to add a short sleep:
```diff
--- a/client/comms.c
+++ b/client/comms.c
@@ -467,6 +467,9 @@ __attribute__((force_align_arg_pointer))
 
         pthread_mutex_unlock(&spMutex);
 
+        // sleep needed to force scheduler to let main thread get its hand on spMutex if needed
+        msleep(1);
+
         // TODO if error, shall we resync ?
 
         pthread_mutex_lock(&txBufferMutex);
```
Even a `usleep(1)` is enough but not portable.

So that msleep could be a solution but I've still to think about it, maybe we can just skip all that logic and take another approach, TestProxmark just signalling in async way the comm thread to adapt the timings whenever it wants, we don't need a lock and the timings to be adjusted immediately.

**Comment by merlokk** [comment]
for me `msleep(1)` - dont work, but `msleep(10)` works

**Comment by doegox** [comment]
@merlokk please try version I just pushed. I hope I didn't break win32 compilation too much...

**Comment by iceman1001** [comment]
ok,  Great idea @doegox   Much better to let the communication thread deal with it.
I reverted the logic flow,   tested on mingw & ubuntu where it works flawless to swapp between serial ports with **hw connect**.   I tested compiling with btaddon (makefile.platform) and tested on rdv4 without a blue shark and I also tested rdv4 with blue shark.  

Now I am curious how it works for @merlokk 

yes, I pushed to master,  so if all works,  this PR can be closed.

**Comment by merlokk** [comment]
All works, thanks)

**Pull request closed without merging**
