### PR TITLE
Early but functionnal SPIFFS implementation 

### PR DESCRIPTION
**Pull request by cjbrigato**
see #257, UPDATE HF_COLIN accordingly

Was a complicated merge, please correct any mistake or consequences on standard files (Makefile etc).

Let's discuss !

### CODE REVIEW

**Comment by iceman1001** [comment]
Awesome!
Did you run a  MAKE STYLE ?    @doegox  did a neat addition to the makefile so we can enforce better codestyle in a easy way :)

**Comment by cjbrigato** [comment]
Oh no I did not. Definitely nice addition.
Not around for some hours, is it blocking a review anyhow?

**Comment by doegox** [comment]
Good job @cjbrigato !!
ok, far too much for a static review. I reviewed the parts interacting with the existing elements and I tested on my device. Let's merge and fix later whatever issues we could find. It shouldn't break anything in the existing features.

**Comment by iceman1001** [comment]
thats the spirit!

**Comment by cjbrigato** [comment]
Thanks guys! Next pr will be a rework of the standalone which will take configuration file from the spiffs regarding the schemes so there will be no more static schemes and it will be extensible. May even be able to create its own config files when it find new schemes :)

**Comment by iceman1001** [comment]
now that here is the start of a new wave of standalone / device functions.  I see all dump can now be as fast as in your standalone mode.  current mf dump is so slow.

**Comment by cjbrigato** [comment]
Yeah good idea that we can use the spiffs as a buffer for such transfer. But regarding the dump function I never used it : provide the key to emulator, but I use ecfill, and save emulator memory to file. It was always very quick, well at least with your fork in old days before the necessary was merged on original repo. Anyway spiffs has no real implication on the dumping speed if you use this method.
I've already made a to my standalone for having support needed for reading any schemes through json configuration file. This will be sick addition I'm sure.
Next will be to automatically add the new found schemes to the configuration when we find all keys without already a known scheme. 
I will add default keys as dynamically read from the device, and use circular buffer to test them all and so as a result we should definitely get through a standalone mode very powerful :)
I'll maintain some stats in another file so we know which scheme is actually a singular and anecdotical one and which one is more than that.
I'll add some connected mode to automatically upload results and 'ew schemes once bt connection is made. And then a connected mode where you can switch on a mode which add a darkside/nested triggering when no known keys are found or if there are some missing ones and you are in situation when you can afford these 30sec for such attack.

**Comment by iceman1001** [comment]
current hf mf dump uses x calls to read accessrights  from each sector.  
Then it uses 1 call to read 1 block at the time from client to device. 
Much better to have all that on deviceside.  Read rights,  dump mem with the keys in a dump keys file?  and when every you want a copy ,  dump to the client is an simple download :) much faster.


your new json styled config was neat.   still,  BT transfers is slow,  so use NG format and keep comms to the minimun

**Pull request merged**
