### PR TITLE
Fix the steps when updating from old version

### PR DESCRIPTION
**Pull request by wh201906**
The steps in `client/src/flash.c` doesn't work for Windows users.
When updating from a old version on Windows, the `pm3-flash-all` always fails even after updating the bootloader. This is because it detects  the hardware by the serial number `ICEMAN`, which only appears after flashing the fullimage.
https://github.com/RfidResearchGroup/proxmark3/blob/48827699deed5589dd6e95668e054ffcc408f3ee/pm3#L144-L150

After flashing bootloader(Serial Number is empty)
图片

After flashing bootloader and fullimage
图片

### CODE REVIEW

**Comment by wh201906** [comment]
To simulate it, I flashed the official firmware then behaved as a newbie trying to flash the latest RRG firmware on Windows.
I did all these steps in series.
1. run `pm3-flash-all.bat`
<details>
<summary>result</summary>

```
[!] Using pm3-flash-all on an oudated bootloader, use pm3-flash-bootrom first!
```

</details>

***
2. run `pm3-flash-fullimage.bat`
<details>
<summary>result</summary>

```
[!!] ====================== OBS ! ===========================================
[!!] Note: Your bootloader does not understand the new CMD_BL_VERSION command
[!!] It is recommended that you first update your bootloader alone,
[!!] reboot the Proxmark3 then only update the main firmware


[!!] ------------- Follow these steps -------------------

[!!]  1)   ./pm3-flash-bootrom
[!!]  2)   ./pm3-flash-all
[!!]  3)   ./pm3

[=] ---------------------------------------------------

[=] Available memory on this board: UNKNOWN

[!!] ====================== OBS ! ======================================
[!!] Note: Your bootloader does not understand the new CHIP_INFO command
[=] Permitted flash range: 0x00102000-0x00140000
[+] Loading usable ELF segments:
[+]    1: V 0x00102000 P 0x00102000 (0x00047d94->0x00047d94) [R X] @0xb8
[!!] Error: PHDR is not contained in Flash
[!!] Firmware is probably too big for your device
[!!] See README.md for information on compiling for platforms with 256KB of flash memory
[!] The flashing procedure failed, follow the suggested steps!
[+] All done

[=] Have a nice day!
```

</details>

(Now I should follow the steps)
***
3. run `pm3-flash-bootrom.bat`
<details>
<summary>result</summary>

```
[!!] ====================== OBS ! ===========================================
[!!] Note: Your bootloader does not understand the new CMD_BL_VERSION command
[!!] It is recommended that you first update your bootloader alone,
[!!] reboot the Proxmark3 then only update the main firmware


[!!] ------------- Follow these steps -------------------

[!!]  1)   ./pm3-flash-bootrom
[!!]  2)   ./pm3-flash-all
[!!]  3)   ./pm3

[=] ---------------------------------------------------

[=] Available memory on this board: UNKNOWN

[!!] ====================== OBS ! ======================================
[!!] Note: Your bootloader does not understand the new CHIP_INFO command
[=] Permitted flash range: 0x00100000-0x00140000
[+] Loading usable ELF segments:
[+]    0: V 0x00100000 P 0x00100000 (0x00000200->0x00000200) [R X] @0x94
[+]    1: V 0x00200000 P 0x00100200 (0x00000d1c->0x00000d1c) [R X] @0x298

[+] Flashing...
[+] Writing segments for file: bootrom.elf
[+]  0x00100000..0x001001ff [0x200 / 1 blocks]
. ok
[+]  0x00100200..0x00100f1b [0xd1c / 7 blocks]
....... ok

[+] All done

[=] Have a nice day!
```

</details>

(The result shows I acturally flashed the bootrom in this step)
***
4. run `pm3-flash-all.bat`
<details>
<summary>result</summary>

```
[!] Using pm3-flash-all on an oudated bootloader, use pm3-flash-bootrom first!
```

</details>

This is unexpected for users, because the steps in the result of step 2 shows I should run `pm3-flash-all.bat` after flashing the bootloader. Users might run `pm3-flash-bootrom.bat` again according to the prompt then fall into a endless loop.
***
The right way is to run `pm3-flash-fullimage.bat` after flashing the bootloader
<details>
<summary>result</summary>

```
[=] Available memory on this board: 512K bytes

[=] Permitted flash range: 0x00102000-0x00180000
[+] Loading usable ELF segments:
[+]    1: V 0x00102000 P 0x00102000 (0x00047d94->0x00047d94) [R X] @0xb8
[+]    2: V 0x00200000 P 0x00149d94 (0x00001ba0->0x00001ba0) [R X] @0x47e50
[=] Note: Extending previous segment from 0x47d94 to 0x49934 bytes

[+] Flashing...
[+] Writing segments for file: fullimage.elf
[+]  0x00102000..0x0014b933 [0x49934 / 589 blocks]
...................................................................
        @@@  @@@@@@@ @@@@@@@@ @@@@@@@@@@   @@@@@@  @@@  @@@
        @@! !@@      @@!      @@! @@! @@! @@!  @@@ @@!@!@@@
        !!@ !@!      @!!!:!   @!! !!@ @!@ @!@!@!@! @!@@!!@!
        !!: :!!      !!:      !!:     !!: !!:  !!! !!:  !!!
        :    :: :: : : :: :::  :      :    :   : : ::    :
        .    .. .. . . .. ...  .      .    .   . . ..    .
...................................................................
...................................................................
................ ok

[+] All done

[=] Have a nice day!
```

</details>

**Comment by iceman1001** [comment]
Hey there,
Just to make sure,  you are on latest source?  
And you are on Proxspace, 


I am a bit surprised to see your findings.

1. if  pm3-flash-bootrom  is ok,
2. pm3-flash-all script flashes bootrom and then fullimage in one go.  Shouldn't be a difference between it and flash-fullimage only.

If you try the repo natively vs running proxspace,   do you have the same findings going from unknown firmware or official to iceman?

**Comment by wh201906** [comment]
> Just to make sure, you are on latest source?
> And you are on Proxspace,

I just use the pre-built binary from this.
https://www.proxmarkbuilds.org/rrg_other/rrg_other-20221029-1f75adcf6d94e52e644d0e903b93072ff527e63c.7z

**Comment by iceman1001** [comment]
I see,   makes sense with the check in the get_pm3_list_windows() that flashing fullimage works. 
Thanks!

**Pull request merged**
