### PR TITLE
Makefile restruct

### PR DESCRIPTION
**Pull request by doegox**
tmp PR to get our CI working on it

### CODE REVIEW

**Comment by merlokk** [comment]
```
[*] MAKE fpga_compress/clean
cp: tools/fpga_compress/fpga_compress: No such file or directory
make: *** [fpga_compress/clean] Error 1
```
make clean error

**Comment by doegox** [comment]
Bummer. I'll fix tonight.
@merlokk could you make brew looking at tool/fpga_compress dir for fpga_compress? And remove the cp hack in master. It will be cleaner. Thanks!!

**Comment by doegox** [comment]
Btw I think fpga_compress doesn't need to be "installed" by brew at all. It's only needed during compilation.

**Comment by iceman1001** [comment]
yeah, I was thinking of that.  its only used during compilation.  We dont want to spread out our executables on the OS.  client and flasher is good enough.
I guess we can go with renaming our flasher for the **make install** idea.
or a symlink.     

- proxmark3  ->  proxmark3-client
- flasher  ->  proxmark3-flasher

**Comment by doegox** [comment]
ok, my PR is ready for review and merge :)
Please go ahead, test it, make it failing!

**Pull request merged**
