### PR TITLE
fix broken keycheck procedure in staticnested process

### PR DESCRIPTION
**Pull request by horrordash**

### CODE REVIEW

**Comment by horrordash** [comment]
I think some clarification is needed here :)
in fact, the command parameters are inserted into the packet in the function mfCheсkKeys. when it is called a block of data should contain only keys. fix removes duplicate command parameters, otherwise the search for keys does not work

**Comment by iceman1001** [comment]
Thanks for the explanation.
That code smells.  I rather would have a struct_t instead of those assignments.  Which would make things easier to understand whats going on.

**Comment by iceman1001** [comment]
ok,  Looks like the `mfCheckKeys` call adds the header itself.
but the problem is that `mfCheckKeys_file` call doesn't add a header.

So this PR needs to adapt to both use-cases.

line 670-675  needs to be different according it `IfPm3Flash()` == true or not.

Does this make sense to you?

**Comment by iceman1001** [comment]
@horrordash   Would you mind pulling latest and test,  I believe I got the correct process.

**Pull request closed without merging**
