### PR TITLE
Rename 77-pm3-usb-device-blacklist in makefile

### PR DESCRIPTION
**Pull request by Foosec**
To align with the changes made in #1894

### CODE REVIEW

**Comment by Foosec** [comment]
Converted to draft, bad fix since it assumes dialout over uucp. Could add Linux check to udev target, and add udev to install. Waiting to hear preferred fix.

**Comment by henrygab** [comment]
This appears to be a regression from my change.  I missed this reference to the udev rules, sorry!

The logic used elsewhere, and which I [duplicated](https://github.com/henrygab/proxmark3/blob/01d30e14fc80505f6bacf6efd71c8c3201aef939/Makefile#L258-L267) in my change:

```
ifneq ($(wildcard /etc/arch-release),)
	# If user is running ArchLinux, use group 'uucp'
	$(SUDO) cp -rf driver/77-pm3-usb-device-blacklist-uucp.rules    $(DESTDIR)$(UDEV_PREFIX)/77-pm3-usb-device-blacklist.rules
else
	# Else, use group 'dialout'
	$(SUDO) cp -rf driver/77-pm3-usb-device-blacklist-dialout.rules $(DESTDIR)$(UDEV_PREFIX)/77-pm3-usb-device-blacklist.rules
endif
```

Perhaps you can use the same conditions in that other makefile location?

**Comment by henrygab** [comment]
@Foosec -- The regression was caused by my failing to test the `install` path.

I think PR #1903 may be what you were trying for.   Can you try it out, and let me know if it resolves your issue?

**Comment by Foosec** [comment]
> 
It does, i was looking for a way to leave that logic in the udev target, perhaps make the udev target a dependency of install, and rather check in udev if the system is linux or not?

**Comment by henrygab** [comment]
> _[[PR #1903]]_ does _[[resolve the issue]]_, i was looking for a way to leave that logic in the udev target, perhaps make the udev target a dependency of install, and rather check in udev if the system is linux or not?

Thanks for confirming this resolves the issue!  I'll leave #1903 open, as it resolves the immediate issue.

That said, I think making the `udev` target a dependency of `install` makes sense, and I'll look forward to seeing your PR with that change!

**Comment by Foosec** [comment]
Fixed in #1903 Thank you @henrygab for your quick reaction!

**Pull request closed without merging**
