### PR TITLE
APDU finder: Reset the tag every x seconds (default is 5 minutes).

### PR DESCRIPTION
**Pull request by ikarus23**

### CODE REVIEW

**Comment by iceman1001** [comment]
Isn't the activate_field always true?    If so the field is dropped and turned on each iteration.

**Comment by ikarus23** [comment]
So far, yes. `activate_field` is always true. But `keep_field_on` is also true, so I figured if the field is still on, `activate_field` is ignored (no need to activate it.

**Comment by iceman1001** [comment]
You need to follow the code paths...

**Comment by ikarus23** [comment]
So what you are tying to say is: "no, the filed is deactivated before it is reactivated if `activate_filed` is true."

**Comment by ikarus23** [comment]
Should be fixed.

**Pull request merged**
