### PR TITLE
Cross compilation

### PR DESCRIPTION
**Pull request by xianglin1998**

### CODE REVIEW

**Comment by xianglin1998** [comment]
Hahahaha, now cross compilation is fully working, please review.

@doegox

**Comment by xianglin1998** [comment]
The reason for deleting an add_custom_command() is because I copied and pasted it to imitate his use, but I forgot to delete it.

**Comment by doegox** [comment]
What bug were you trying to fix with bzip2?
The cmake was made such that the sources were downloaded to client/deps, now it's again in build/deps

**Comment by xianglin1998** [comment]
built it download.cmake The problem of disappearing. It seems that this problem is caused by the specification of source directory. I put the temporary files outside to solve this problem.

**Comment by xianglin1998** [comment]
image

I got this error at build.

**Comment by xianglin1998** [comment]
image

But it seems to have been downloaded successfully.

image

When I change PREFIX or SOURCE_DIR,  This problem can be solved, so I  guess that these two directories cannot use the same path.

**Comment by doegox** [comment]
What is your environment ? Debian? WSL/Ubuntu? ...
Could you repeat with `make VERBOSE=1 2>&1 | tee make.log` and share all the build directory in a zip ?

**Comment by doegox** [comment]
Also I don't recognize your screenshot, in which path is it ? There shouldn't be a `src` there.
You should have:
* `client/deps/bzip2/` containing all these files + `.git/`, that's the result of git clone bzip2
* `client/build-android/deps/bzip2/src/bzip2` containing a copy of all these files (client/build-android or whatever is your build dir)
The copy occurs with the `CONFIGURE_COMMAND     mkdir -p ${BZIP2_BUILD_DIR} && git archive --format tar HEAD | tar -C ${BZIP2_BUILD_DIR} -x` step. I think that step goes wrong on your machine

**Comment by xianglin1998** [comment]
I am build on Ubuntu.

**Comment by xianglin1998** [comment]
Yes, this may have peoblem on my computer.

**Comment by doegox** [comment]
Here is a trace on my Debian with VERBOSE=1 so you can compare
```
Scanning dependencies of target bzip2
make[2]: Leaving directory '/home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android'
make -f CMakeFiles/bzip2.dir/build.make CMakeFiles/bzip2.dir/build
make[2]: Entering directory '/home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android'
[  5%] Creating directories for 'bzip2'
/usr/bin/cmake -E make_directory /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/deps/bzip2
/usr/bin/cmake -E make_directory /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/deps/bzip2
/usr/bin/cmake -E make_directory /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2
/usr/bin/cmake -E make_directory /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/tmp
/usr/bin/cmake -E make_directory /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2-stamp
/usr/bin/cmake -E make_directory /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src
/usr/bin/cmake -E make_directory /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2-stamp
/usr/bin/cmake -E touch /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2-stamp/bzip2-mkdir
[  7%] Performing download step (git clone) for 'bzip2'
cd /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/deps && /usr/bin/cmake -P /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2-stamp/bzip2-download-.cmake
-- bzip2 download command succeeded.  See also /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2-stamp/bzip2-download-*.log
cd /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/deps && /usr/bin/cmake -E touch /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2-stamp/bzip2-download
[  7%] No patch step for 'bzip2'
/usr/bin/cmake -E echo_append
/usr/bin/cmake -E touch /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2-stamp/bzip2-patch
[  7%] Performing update step for 'bzip2'
cd /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/deps/bzip2 && /usr/bin/cmake -P /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/tmp/bzip2-gitupdate.cmake
[  8%] Performing configure step for 'bzip2'
cd /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/deps/bzip2 && mkdir -p /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2 && git archive --format tar HEAD | tar -C /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2 -x
cd /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/deps/bzip2 && /usr/bin/cmake -E touch /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2-stamp/bzip2-configure
[  8%] Performing build step for 'bzip2'
cd /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/deps/bzip2 && make -C /home/phil/devel/00smartcard/readers/proxmark/proxmark3-RRG.git/client/build-android/deps/bzip2/src/bzip2 -j4 CC=/home/phil/devel/00android/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang CXX=/home/phil/devel/00android/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ LD=/home/phil/devel/00android/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/clang AR=/home/phil/devel/00android/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar RANLIB=/home/phil/devel/00android/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib CFLAGS=--target=armv7-none-linux-androideabi19 libbz2.a
```

**Comment by xianglin1998** [comment]
image

This is my path.

**Comment by doegox** [comment]
your path seems completely wrong indeed, could you run with `make VERBOSE=1 2>&1 | tee make.log` and share all the proxmark3 dir in a zip ?

**Comment by xianglin1998** [comment]
Ok， plz wait.

**Comment by xianglin1998** [comment]
image

What, I suddenly found that I didn't find any path definition of build-android. Is this my problem?

**Comment by doegox** [comment]
no no build-android is just my build because I call the cross-compilation with
```sh
cd client
rm -rf build-android
mkdir build-android
(
  cd build-android
  cmake -DCMAKE_TOOLCHAIN_FILE=~/devel/00android/android-ndk-r21/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=android-19 -DSKIPBT=1 -DSKIPPYTHON=1 -DSKIPPTHREAD=1 ..
  make VERBOSE=1 2>&1 | tee make.log
#  make -j
)
```
I tried on Ubuntu 20.04 and it worked fine.
Did you try removing entirely your build dir and the dir `client/deps/bzip2` before your test?

**Comment by xianglin1998** [comment]
Yes, i do. i clone from RRG repo, It's brand-new, but i always get this error.

**Comment by doegox** [comment]
what are the commands you perform ?

**Comment by xianglin1998** [comment]
1. cd to pm3_rrg

2. git clone from RRG repo

3. cd proxmark3

4. cmake -DCMAKE_TOOLCHAIN_FILE=/home/dxl/ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-19 -DSKIPPTHREAD=1 CmakeLists.txt

5. wait ... wait ... wait ... WOW, get this error successfully. :(

**Comment by iceman1001** [comment]
I think you should target armeabi-v7a  for that is what the Proxmark3 has.  Not arm64-v8a?

**Comment by xianglin1998** [comment]
This only affects clang's target selection. I don't think it will cause such directory problems. Maybe this is the compatibility problem of cmake?

**Comment by xianglin1998** [comment]
Yes, we can remove "unused". but It's from external lib, so can i add a clang parameter to dissable that warnning?

@iceman1001

**Comment by doegox** [comment]
cmake is made to be called from a build directory to avoid the mess.
Try
```
cd proxmark3/client
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=/home/dxl/ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=android-19 -DSKIPPTHREAD=1 ..
make
```

**Comment by doegox** [comment]
> I think you should target armeabi-v7a for that is what the Proxmark3 has. Not arm64-v8a?

We're not compiling the ARM firmware, we're compiling a client for Android.
Visibly, DXL smartphone is an arm64-v8a, so nothing to worry about

**Comment by iceman1001** [comment]
Since it is external lib,   and we are not responsible for that one,  we might aswell just hide it.

**Comment by iceman1001** [comment]
>     I think you should target armeabi-v7a for that is what the Proxmark3 has. Not arm64-v8a?
> We're not compiling the ARM firmware, we're compiling a client for Android.
> Visibly, DXL smartphone is an arm64-v8a, so nothing to worry about

Naturally and makes more sense

**Comment by xianglin1998** [comment]
Use your cmd, i can build successfully. this is a small problem, can you add some tips or a cross_build.sh? :)

@doegox

**Comment by doegox** [comment]
DXL we had already some, I added the basics: https://github.com/RfidResearchGroup/proxmark3/blob/master/client/CMakeLists.txt#L1-L19

**Comment by xianglin1998** [comment]
Wow, nice. now cross compilation is very easy. thanks for you and iceman.

**Comment by doegox** [comment]
thanks to *you* sir :)

**Comment by iceman1001** [comment]
> DXL we had already some, I added the basics: https://github.com/RfidResearchGroup/proxmark3/blob/master/client/CMakeLists.txt#L1-L19

We need to have a_notes on cross compilation_ document.


And yes,  thank you @xianglin1998 for enable android builds and now we have a nice solution that works.   🙏

**Comment by doegox** [comment]
> We need to have a_notes on cross compilation_ document.

Currently we don't have any user doc on cmake, only official way is Makefile. I suggest we do it when we're ready to have cmake as the default approach for compiling the client, and we add the cross-compilation info at the same time.

We're not that far, see the table, mainly warnings management, cpu for hardnested, Lua stuff and `make install` and we're good.

**Pull request closed without merging**
