### PR TITLE
Decode MAD Info Byte and show info about sector it points to

### LINKED ISSUE #766: [idea] Mifare MAD - Card publisher sector enhancement
Now that we have the MAD database, we can perhaps enhance the Card publisher sector info:

```
[=] --- MAD Information -------------------------------
[=] ---------------------------------------------------
[+] Card publisher sector: 0x01
[=]  00 MAD 1
[=]  01 [7006] Hotel, access contr. & sec [Vingcard a.s.]
[=]  02 [7005] Energy Saving System For Hotels, Access Control [ENKOA System]
[=]  03 [7007] Hotel, access contr. & sec [Vingcard a.s.]
[=]  04 [7007] (continuation)
[=]  05 [7007] (continuation)
[=]  06 [7009] Access control data for electronic locks [Timelox AB]
[=]  07 [0000] (free)
[=]  08 [0000] (free)
[=]  09 [0000] (free)
[=]  10 [0000] (free)
[=]  11 [0000] (free)
[=]  12 [0000] (free)
[=]  13 [0000] (free)
[=]  14 [0000] (free)
[=]  15 [0000] (free)
```

Would be cool to actually read `Vingcard a.s.` from the sector1's info and list it with `Card publisher sector`.
Some refactoring might be needed as `Card publisher sector` is printed out before we know if MAD2 is supported and it *may* point into MAD2.

IMHO the best way to go about it is first parse (`MADDecode`), then print out output using the parsed data with `MAD1DecodeAndPrint` and `MAD2DecodeAndPrint`.

Feel free to assign to me if possible, I'll try to find some time for this soon.

### PR DESCRIPTION
**Pull request by lukaskuzmiak**
This closes #766

### CODE REVIEW

**Comment by iceman1001** [comment]
Don't forget to add a line in CHANGELOG.md

**Comment by iceman1001** [comment]
Question,  in what way do you think the printing of the line that we don't have before?
Is it the Sector 1 is Card publisher sector?  then we don't need the extra text,   we could just add a hint on the line  01 instead.   Makes for a more dense format.
```
01 [7006] Hotel, access contr. & sec [Vingcard a.s.]  (card publisher sector)
```
image

**Comment by lukaskuzmiak** [comment]
So, the sector is:

> The information of the card publisher sector is particularly useful if somebody needs to find out the organization responsible for distribution of free card sectors for new
applications."

Ideally I would just print `company` out of that sector, but the `print_aid_description` kinda parses and prints all of it and it didn't seem worth changing the whole thing for just the company.

If you prefer a hint on the sector line instead, I can try that. Getting used to how things work around here, sorry if that's too verbose :-)

**Comment by iceman1001** [comment]
Since we already print company,   adding a color on the sector line to emphase would be a nicer output.   Just go to yourself,  would you want to read the same info again?  Would that make it clearer?

So in the case above,   knowing that its Vingcard a.s.  that is reponsible would be the interesting bit.
Its a bit redundant now,  we can make it more crisp.

**Pull request merged**
