### PR TITLE
Electra branch

### PR DESCRIPTION
**Pull request by doegox**
Not so easy to get a smooth integration of Electra support.
Please have a look before merging.

### CODE REVIEW

**Comment by doegox** [comment]
Example:
image

When parity also matches an EM XL ID:
image

**Comment by doegox** [comment]
Line "Possible an Electra" doesn't appear if extra data is more than 3 niggles + zeroes.

**Comment by iceman1001** [comment]
Cool,  and yes,   that was some nestled ifs to make this happen

**Comment by NoSoup** [comment]
Hey, thank you for your work on adding support for electra. I've tried it just now with the changes from master and with a tag from Electra (from my intercom). Unfortunately `lf search` wasn't able to identify it :(.

**Comment by doegox** [comment]
@NoSoup There are apparently different versions of Electra tag. 
Do you get some signal with `lf read` + `data plot` ? 
If yes, can you share the trace ? `data save -f myelectrafile`
You can reach me on the Discord server if that's easier

**Pull request merged**
