### PR TITLE
define proxguiqt.cpp depends to avoid parallel/shuffle build failure

### PR DESCRIPTION
**Pull request by ZeroChaos-**
https://github.com/RfidResearchGroup/proxmark3/issues/2062

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
This is confirmed/tested to fix the reported bug.  I'm going to burn some cpu time looking for any more of these while I'm here.  Feel free to not merge right away.

**Comment by ZeroChaos-** [comment]
Those check failures look unrelated to me.  Can anyone confirm?

**Comment by iceman1001** [comment]
totally unrelated to you.

**Comment by ZeroChaos-** [comment]
Testing complete, this is good to go!

**Pull request merged**
