### PR TITLE
Add contact interface to PCSC passthrough

### PR DESCRIPTION
**Pull request by gm3197**
- Rename `smart relay` to `smart pcsc`
- Add options to select which interfaces to use: `-a` (14a contactless), `-b` (14b contactless), `-c` (contact)
- See [this conversation](https://github.com/RfidResearchGroup/proxmark3/pull/2030#issuecomment-1817233194) for motivation

### CODE REVIEW

**Comment by iceman1001** [comment]
you have some issues with the white space,  

run `make style` ,

**Comment by gm3197** [comment]
Yes, did I miss something?

**Comment by iceman1001** [comment]
Yeah,  your generated command.json / command.doc  is old.    So your setup doesn't seem to have the latest source code.

**Comment by iceman1001** [comment]
and there is diff errors inside...    

How about you clean up your PR?

**Comment by iceman1001** [comment]
I cleaned up your PR and pushed it.

https://github.com/RfidResearchGroup/proxmark3/commit/c3e269d1b6e7ccc5e66d71635223d3f8f7ed438a

**Pull request closed without merging**
