### PR TITLE
Update Android Termux guide

### PR DESCRIPTION
**Pull request by ViRb3**
No more ncurses hacking, no more Makefile modifications!

### CODE REVIEW

**Comment by iceman1001** [comment]
Why?  What has changed?

**Comment by ViRb3** [comment]
Termcap was included in the official ncurses package, so no need to build and install it manually anymore. Also compilation succeeds without adding -fPIC to the Makefile.

**Comment by netvader** [comment]
I can confirm that, works perfectly, thanks for the update!

**Comment by doegox** [comment]
yep, tested, thanks.

**Comment by iceman1001** [comment]
Excellent!

**Pull request merged**
