### PR TITLE
reworked the README.md file

### PR DESCRIPTION
**Pull request by ikarus23**
* Restructured content
* Corrected install instrucitons (for Linux)
* Corrected ModemManager issue
* Used consistent formatting
* Fixed typos

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice one,  however @5w0rdfish is doing a total remake of this one.   You find it here,  https://github.com/5w0rdfish/proxmark3   How about you look at that one and see if you can improve it?

**Comment by ikarus23** [comment]
I can't open an issue over at @5w0rdfish's fork to inform her. But she is very welcome to copy parts of my reworked readme to her install instructions. Especially the install instructions (mainly for Linux) were not that good. Also, the formatting should be more consistent.

**Comment by 5w0rdfish** [comment]
Hi @ikarus23 , currently working my way through reviewing and testing each OS, just about to work on Linux again so thanks!, I can cross check against my notes and make some adjustments if needed, and the Read.me has had some big changes structurally, along with the other pages so the style should be consistent by the end of it :).

**Comment by ikarus23** [comment]
@5w0rdfish Great! Feel free to contact me if you need some reviewing for the Linux part (especially Arch Linux) ;)

**Comment by 5w0rdfish** [comment]
That would be brilliant! do you want to re-write the Arch page?. I have separated out the different OS into their own pages now. I'm not an Arch user so your input would be really welcomed. 
Sending you an email now :)

**Comment by iceman1001** [comment]
@ikarus23  if you sort out things with @5w0rdfish  meanwhile close this one?

**Comment by ikarus23** [comment]
Yep.

**Pull request closed without merging**
