### PR TITLE
cmdlfpac - add decode / encode card ID

### PR DESCRIPTION
**Pull request by danshuk**

### CODE REVIEW

**Comment by iceman1001** [comment]
Amazing,  you figured PAC/Stanley out.  I am impressed and curious to how you did it.

Before I merge,  Don't forget to add a row in CHANGELOG.md

**Comment by iceman1001** [comment]
Excellent!  Great contribution!

**Comment by danshuk** [comment]
Thanks. I bought a reader and a bunch of tags off ebay and spent a while studying the demods and IDs, plus a little reversing of the admin tool...

**Comment by iceman1001** [comment]
Can't find your email,  so I will ask here. 
Do you have a pac/stanley trace file that you can add to the /traces folder?  Makes things easy to test that the de/encode parts.

**Comment by danshuk** [comment]
No problem, I'll create another pr with a trace file added.

**Comment by iceman1001** [comment]
:)
Still don't have your email..  or signal or keybase, so I write here.
I added most of the needed nrz sim stuff.  Just need to find the correct bitpattern for a nrz wave form :)
And a cardid to bits... But that one is for you

**Comment by danshuk** [comment]
Awesome! Looks like there's not much left for me to do :) I'll get it done this weekend 👍

I also dropped you a quick email :)

**Pull request merged**
