### PR TITLE
Support of Mifare Classic Super Gen2

### PR DESCRIPTION
**Pull request by AloneLiberty**
Introduce new gen2 super card with ability to recover up to 3 different keys from it (and super card docs improve). 
Should detect gen1/gen2 cards:
image
And recover up to 3 different keys from gen2:
image

### CODE REVIEW

**Comment by iceman1001** [comment]
I am curious if _COPYKY NSCK II_   is a super card...

**Comment by iceman1001** [comment]
@AloneLiberty   is it ready to merge?

**Comment by AloneLiberty** [comment]
> @AloneLiberty is it ready to merge?

Yes

**Comment by iceman1001** [comment]
Excellent

**Pull request merged**
