### PR TITLE
Add SUBE keys (Argentina public transportation system card)

### PR DESCRIPTION
**Pull request by CONIGUERO**

### CODE REVIEW

**Comment by iceman1001** [comment]
IS this unique keys or are the system using diversified keys?   ie individual keys for each card

**Comment by CONIGUERO** [comment]
> IS this unique keys or are the system using diversified keys? ie individual keys for each card

These are universal keys, however some card variants have different ones. Depends on the year of manufacture. All cards of the 2017 variant will have the same keys for example, while all the 2015 ones will have a different set but it will work on all cards made in 2015.

**Comment by iceman1001** [comment]
Thats good.  

but... you removed all comments in your PR.   Just add the keys please.

**Comment by iceman1001** [comment]
I added your keys,  closing this one.

https://github.com/RfidResearchGroup/proxmark3/commit/1b6b16d91a7546ce01339f02664005555a42807a

**Pull request closed without merging**
