### PR TITLE
Fix units

### PR DESCRIPTION
**Pull request by wh201906**
According to the [Wikipedia](https://en.wikipedia.org/wiki/Kilobyte), 
`kb` means kilobits in base 10, 1kb=1000b
`KB` means kilobytes in base 2, 1KB=1024B

Some unit symbols in the documents and codes are misleading, so I fixed them.

### CODE REVIEW

**Comment by iceman1001** [comment]
are you sure that the values are measured in kb vs KB where you changed?

**Comment by wh201906** [comment]
For the skip parameters I'm not sure if it's `kB` or 'KB', but it's definitely not `kb`
https://github.com/RfidResearchGroup/proxmark3/pull/1956/files#diff-b6447582c99244aba3abf3b2dbe66e10fa20789a7b9818cb3a02e1176fdef171L158-L173

For the rest of the PR I'm pretty sure.

**Comment by iceman1001** [comment]
in that case you need to verify it...

**Comment by wh201906** [comment]
OK

**Comment by wh201906** [comment]
I tested some of the `SKIP` options on the commits in which the document was modified. I can't reproduce the exact number in the document, but in all cases `KB` is closer to the result in the document.

***

Most of the reduced size of `SKIP` options is added in commit b2bc2a499dfa14cf42b29b627ea61ab1efe62648

<details><summary>Tested on commit b2bc2a499dfa14cf42b29b627ea61ab1efe62648</summary>

258.6 kB (258,640 Bytes)
```
PLATFORM=PM3OTHER
PLATFORM_SIZE=256
STANDALONE=
INSTALLSUDO=sudo
```

258.1 kB (258,120 Bytes) -520 Bytes=0.520kB=0.508KB
expected: 0.5
```
PLATFORM=PM3OTHER
PLATFORM_SIZE=256
STANDALONE=
SKIP_HFSNIFF=1
INSTALLSUDO=sudo
```

254.5 kB (254,532 Bytes) -4108 Bytes=4.108kB=4.012KB
expected: 4.0
```
PLATFORM=PM3OTHER
PLATFORM_SIZE=256
STANDALONE=
SKIP_FELICA=1
INSTALLSUDO=sudo
```

233.6 kB (233,564 Bytes) -25076 Bytes=25.076kB=24.488KB
expected: 24.2
```
PLATFORM=PM3OTHER
PLATFORM_SIZE=256
STANDALONE=
SKIP_HITAG=1
INSTALLSUDO=sudo
```

193.3 kB (193,256 Bytes) -65384 Bytes=65.384kB=63.852KB
expected: 63.0
```
PLATFORM=PM3OTHER
PLATFORM_SIZE=256
STANDALONE=
SKIP_ISO14443a=1
INSTALLSUDO=sudo
```

</details>

***

The reduced size of `SKIP_ZX8211` option is added in commit 76846ae1869c51aaeceaf1e22acac7f13e889198

<details><summary>Tested on commit 76846ae1869c51aaeceaf1e22acac7f13e889198</summary>

301.5 kB (301,508 Bytes)
```
PLATFORM=PM3GENERIC
PLATFORM_SIZE=256
STANDALONE=
INSTALLSUDO=sudo
```

301.1 kB (301,144 Bytes) -364 Bytes=0.364kB=0.355KB
expected: 0.3
```
PLATFORM=PM3GENERIC
PLATFORM_SIZE=256
STANDALONE=
SKIP_ZX8211=1
INSTALLSUDO=sudo
```

</details>

**Comment by iceman1001** [comment]
Sounds good to me,  
merged!

**Pull request merged**
