### PR TITLE
Add hint for iClass in `hf search`

### PR DESCRIPTION
**Pull request by bettse**
It was:

```
[usb] pm3 --> hf search
 🕙  Searching for iCLASS / PicoPass tag...   
[+] iCLASS / Picopass CSN: CE F0 43 01 F7 FF 12 E0 

[+] Valid iCLASS tag / PicoPass tag found
```

And now it is 

```
[usb] pm3 --> hf search
 🕗  Searching for iCLASS / PicoPass tag...   
[+] iCLASS / Picopass CSN: CE F0 43 01 F7 FF 12 E0 

[+] Valid iCLASS tag / PicoPass tag found

[?] Hint: try `hf iclass` commands
```

### CODE REVIEW

**Comment by iceman1001** [comment]
This is divider...

either we have hints for all positive identifications,     and should they come direct after each one or all hint goes in the bottom like the rest of the client does. 
or we don't have hints because its one type per identification compared with it is not "unknown" positives like for `hf 14a info`   which can be a range of types.

hm....

Lets go with hints but I want them to be all in the end,     like we do in other places in the client.

**Comment by bettse** [comment]
> Lets go with hints but I want them to be all in the end, like we do in other places in the client.

I've not been in this area before, so I'm uncertain of the implication.  Does that mean I should setup a variable that saves that it was iClass, and then create a conditional after all the checks that would output the hint?

**Comment by iceman1001** [comment]
yes  that is correct.  And add hints for the other checks too,  please.

**Comment by bettse** [comment]
> And add hints for the other checks too, please.

That would be beyond the scope of what I'm looking to achieve: is that a requirement for the PR?

**Comment by bettse** [comment]
😮  I was working on the change to put the hint at the end, I just didn't want to introduce the other hints.

**Comment by iceman1001** [comment]
yeah,  I understand.

**Pull request merged**
