### PR TITLE
Work directory supported. 

### PR DESCRIPTION
**Pull request by xianglin1998**

### CODE REVIEW

**Comment by xianglin1998** [comment]
Now i am coding at naming conventions. plz review. thank you.  : )

**Comment by iceman1001** [comment]
Excellent!

For the next time,  you can remove `_my_` in your global vars since you are following the naming convention now

**Comment by xianglin1998** [comment]
ok. ：）

**Comment by doegox** [comment]
for info, you don't need to close a PR and open another one referring to the same branch.
When you pushed a new commit to the branch, it's automatically available in the existing PR. 
See https://github.com/RfidResearchGroup/proxmark3/pull/740/commits

**Pull request merged**
