### PR TITLE
Mifare MAD application code & cluster code swapped?

### PR DESCRIPTION
**Pull request by lukaskuzmiak**
Hey, I believe the Mifare MAD decoding is byte swapped by accident. According to [NXP's description on Mifare Application Directory](https://www.nxp.com/docs/en/application-note/AN10787.pdf), section 2.1 - bit0 to bit7 is an application code and bit8 to bit15 is function cluster code.

I have a few hotels cards (VingCard I believe) and they show this:

```
[usb] pm3 --> hf mf mad
Card publisher sector: 0x01
00 MAD1
01 [0670] cluster: miscellaneous applications
02 [0570] cluster: miscellaneous applications
03 [0770] cluster: miscellaneous applications
04 [0770] cluster: miscellaneous applications
05 [0770] cluster: miscellaneous applications
06 [0970] cluster: ferry traffic
07 [0000] free
08 [0000] free
09 [0000] free
10 [0000] free
11 [0000] free
12 [0000] free
13 [0000] free
14 [0000] free
15 [0000] free
```

This is after my pull request:

```
[usb] pm3 --> hf mf mad
Card publisher sector: 0x01
00 MAD1
01 [7006] cluster: hotel
02 [7005] cluster: hotel
03 [7007] cluster: hotel
04 [7007] cluster: hotel
05 [7007] cluster: hotel
06 [7009] cluster: hotel
07 [0000] free
08 [0000] free
09 [0000] free
10 [0000] free
11 [0000] free
12 [0000] free
13 [0000] free
14 [0000] free
15 [0000] free
```

I also believe that MAD2 decoding has yet another issue but I have no testing cards to confirm, the decoding looks like this:

mad.c:134
```
return (sector[2 + (sectorNo - 1) * 2 + 1] << 8) + (sector[2 + (sectorNo - 1) * 2]);
```

However according to the spec, section 3.6, Table 10 - byte 2&3 contain AID for sector 0x11 (17) and therefore I believe it should really be `sectorNo - 17` and not `-1` as this is a continuation of MAD1 - if anybody can comment on that I'd be happy to include that into the PR.

### CODE REVIEW

**Comment by lukaskuzmiak** [comment]
Most of the cards I have follow my PR, I however have one card (Hilton something, so obviously an access card) that has Block 1 as follows:

```
6F 01 5190 5190 0000 0000 0000 0000 0000
```

Which used to translate to `0x5190` (`0x51` - "cluster: access control & security"), vs. it would now be `0x9051` which is `0x90` - "cluster: television".

Now I'm a bit confused about which of these hotel access card vendors messed up :-)

**Comment by iceman1001** [comment]
I think this is a situation of big endian,  little endian problem.
How they wrote the data to the card.  The question becomes if we can find a good way to always detect if so was the case.  

Meanwhile I will close this one,   I have more changes to the code,  which I will push,  so we can have that as a base for when we find a detection.

**Comment by iceman1001** [comment]
Does all of your cards get a valid CRC?   My cards with a MAD,  has invalid crcs.

**Comment by lukaskuzmiak** [comment]
If you mean the 1st byte of the block 1, the CRC8 (the weird MAD CRC with whatever input value, implemented by `CRC8Mad`), then yes, I briefly tried 5 cards I have here (4 VingCard and the 1 weird "television" one I mentioned) and all get `CRC8-MAD1 OK` in verbose mode with `hf mf mad -v`.

IMHO the spec I linked to defines endianness. The Application Identifier table does show "cluster code" being bit8-15. And then the Table 9 does show, eg. "AID for sector 1" being bytes 2 and 3, which IMHO implies bits 8 through 15 are in byte 3.

Do you understand that differently?

Sadly, I do not have many more samples, maybe that 1 card is just a mess up and not statistically significant.

image

image

**Comment by doegox** [comment]
I would also suggest to compare results with NXP TagInfo

**Comment by lukaskuzmiak** [comment]
@doegox somehow I was just doing that :-) Here's a report made by the latest NXP's TagInfo on one of the VingCards. IMHO it is consistent with this PR.

[26-01-85-4D_2020-06-08 22-27-26_taginfo_scan.txt](https://github.com/RfidResearchGroup/proxmark3/files/4750660/26-01-85-4D_2020-06-08.22-27-26_taginfo_scan.txt)

**Comment by doegox** [comment]
I only found 2 samples, only to bring some more confusion :) : 

Kaba hotel key:
```
[0] 53 42 4B 8A D0 89 04 00 C8 51 00 20 00 00 00 15 
[1] 6F 01 51 90 51 90 00 00 00 00 00 00 00 00 00 00 
[2] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[3] 00 00 00 00 00 00 78 77 88 C1 00 00 00 00 00 00 
```
**master** branch:
```
[!] ⚠️  Wrong MAD 1 CRC calculated: 0xe7 != 0x6f
...
[=]  01 [5190] cluster: access control & security
[=]  02 [5190] cluster: access control & security
```
**mifare-mad-fix** branch:
```
[!] ⚠️  Wrong MAD 1 CRC calculated: 0xe7 != 0x6f
...
[=]  01 [9051] cluster: television
[=]  02 [9051] cluster: television
```

NDEF tag:
```
[0] BC C3 1B 76 12 08 04 00 62 63 64 65 66 67 68 69 
[1] 14 01 03 E1 03 E1 03 E1 03 E1 03 E1 03 E1 03 E1 
[2] 03 E1 03 E1 03 E1 03 E1 03 E1 03 E1 03 E1 03 E1 
[3] 00 00 00 00 00 00 78 77 88 C1 00 00 00 00 00 00 
```
**master** branch:
```
[!] ⚠️  Wrong MAD 1 CRC calculated: 0x8f != 0x14
...
[=]  01 [03E1] NDEF
...
[=]  15 [03E1] NDEF
```
**mifare-mad-fix** branch:
```
[!] ⚠️  Wrong MAD 1 CRC calculated: 0x8f != 0x14
...
[=]  01 [03E1] NFC Forum
...
[=]  15 [03E1] NFC Forum
```

I guess the hotel card is better recognized when "access control & security" than "television"
and I see NDEF/NFC Forum is kind of present twice, interpreting both endianess...

**Comment by doegox** [comment]
I'd be in favor of accepting the swap of endianness, so the PR, to be aligned with TagInfo, but to add also an option to swap endianness interpretation from the command line, for those cards that seem to have messed up.
Still the CRC to fix...

**Comment by lukaskuzmiak** [comment]
@doegox well, this is weird. My "television" card is the same as yours (likely a Kaba too I suppose based on your contents, I am not sure about mine).

This is from this branch (`mifare-mad-fix`), I am not quite understanding how the same data produce a different CRC. I am on macOS 10.15.5, not sure if platform can play a role, have no inspected the implementation.
Maybe the CRC bug is unrelated to this and a separate one. I'm attaching the NXP TagInfo report on that card below, the app seems to like the CRC, so not sure.

[B6-25-9B-29_2020-06-09 01-37-34_taginfo_scan.txt](https://github.com/RfidResearchGroup/proxmark3/files/4750912/B6-25-9B-29_2020-06-09.01-37-34_taginfo_scan.txt)

```
[usb] pm3 --> hf mf mad -v
[0] B6 25 9B 29 21 08 04 00 01 29 F7 BA 20 57 66 1D 
[1] 6F 01 51 90 51 90 00 00 00 00 00 00 00 00 00 00 
[2] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[3] 00 00 00 00 00 00 78 77 88 C1 00 00 00 00 00 00 
GPB: 0xc1
Multi application card.
MAD version: 1
CRC8-MAD1 OK.
Card publisher sector: 0x01
00 MAD1
01 [9051] cluster: television
02 [9051] cluster: television
03 [0000] free
04 [0000] free
05 [0000] free
06 [0000] free
07 [0000] free
08 [0000] free
09 [0000] free
10 [0000] free
11 [0000] free
12 [0000] free
13 [0000] free
14 [0000] free
15 [0000] free
[usb] pm3 --> 
```

**Comment by lukaskuzmiak** [comment]
Also, if we agree on the default endianness wanted and/or the option to swap it, I'll be happy to try to implement that, let's coordinate with the changes @iceman1001 mentioned he had.

**Comment by iceman1001** [comment]
Just pull latest,   I see that the output from the mad command needs to be more verbose in some stages.
1.  MAD1  -> more common.
2. MAD2  ->  seen it on vingcard 4k
3. MAD3   -> never seen this-

4.  CRC fix
5. optional endianess,  but I prefer the code to automatically detect it....  Easiest would be adding an option.  `hf mf mad -be`    / `hf mfp mad -be`     and we default to -le.   ie,  merge @lukaskuzmiak 's pr once updated

**Comment by iceman1001** [comment]
Problem with NXP document you linked to and the images,  is that they present bytes in reverse order from PM3.   They are both talking about the same byte, but when looking at it from pm3 way makes it easy to mix it up in your head... like I do....

PM3 way:
```
     00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
[0] 53 42 4B 8A D0 89 04 00 C8 51 00 20 00 00 00 15 
```

PDF:
```
    15 14 13 12 11 10 09 08 07 06 05 04 03 02 01 00
    15 00 00 00 20 00 51 C8 00 04 89 D0 8A 4B 42 53
```

And I think this is the reason for strange implementations in the wild.

**Comment by iceman1001** [comment]
This is a 1K MFC VingCard.   Definitly wrong.  
```
[usb] pm3 --> hf mf mad -v
[0] BB D1 F1 53 C8 98 02 00 E3 41 00 20 00 00 00 14
[1] D5 01 06 70 05 70 07 70 07 70 07 70 09 70 00 00
[2] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[3] 00 00 00 00 00 00 78 77 88 C1 00 00 00 00 00 00
[=] GPB: 0xc1
[=] Multi application card.
[=] MAD version: 1
[!] ⚠️  Wrong MAD 1 CRC calculated: 0xb6 != 0xd5
[=] CRC8-MAD1 (fail)
[=] Card publisher sector: 0x01
[=]  00 MAD 1
[=]  01 [0670] cluster: miscellaneous applications
[=]  02 [0570] cluster: miscellaneous applications
[=]  03 [0770] cluster: miscellaneous applications
[=]  04 [0770] cluster: miscellaneous applications
[=]  05 [0770] cluster: miscellaneous applications
[=]  06 [0970] cluster: ferry traffic
[=]  07 [0000] free
[=]  08 [0000] free
[=]  09 [0000] free
[=]  10 [0000] free
[=]  11 [0000] free
[=]  12 [0000] free
[=]  13 [0000] free
[=]  14 [0000] free
[=]  15 [0000] free
```

**Comment by iceman1001** [comment]
With this PR  :)  All well
image

**Comment by doegox** [comment]
All good here too, including CRCs with last @iceman1001 fix

**Comment by iceman1001** [comment]
I pushed some more textual fixes,  A better flow of the output.   I prepped for a "-be"  argument,   @lukaskuzmiak  if you up to add it to mad.c  that would be great.

**Comment by iceman1001** [comment]
I am curious how NXP taginfo gets this matching....
```
# MIFARE applications:
Multi-application card
Card publisher sector: 1
* Hotel, access contr. & sec
	- Vingcard a.s.
* Energy Saving System For Hotels, Access Control
	- ENKOA System
* Hotel, access contr. & sec
	- Vingcard a.s.
* Access control data for electronic locks
	- Timelox AB
```

**Comment by lukaskuzmiak** [comment]
@iceman1001 saw your textual fixes, I'll check it out later today.
For the TagInfo - IMHO they bundle some sort of DB with their app, if there is interest to maybe incorporate that into `client`, I can try to peek into the APK and see where is that coming from.

**Comment by iceman1001** [comment]
Already,  thanks for the sqlite db,   we have now incorporated it into the repo :)

**Pull request merged**
