### PR TITLE
[WIP] Easy to use build script for MacOS and Linux

### PR DESCRIPTION
**Pull request by adryd325**
In the [wishlist](https://github.com/RfidResearchGroup/proxmark3/wiki/Wishlist), a user friendly build script is wanted. I thought I'd take this on

TODO:
- [ ] Check for and install dependencies if needed (in progress)
- [ ] Check if current working directory is the proxmark repo, or find a location to clone the repo if needed 
- [ ] Ask questions to generate a Makefile.platform file
- [ ] make and make install
- [ ] (Maybe) Ask the user if they'd like to flash their proxmark

### CODE REVIEW

**Comment by iceman1001** [comment]
Awesome!
Feel free to add a line in the CHANGEME.md  file too.

You feel this PR is ready to merge or is it a WIP?

**Comment by adryd325** [comment]
It's an early WIP, hence draft status. i'll add the changelog entry before marking as ready for review

**Comment by iceman1001** [comment]
Cool,

**Comment by iceman1001** [comment]
How is the work going on this?

**Comment by adryd325** [comment]
My lifes TODO list has gotten far too long, both burned out and have to focus on school. I'd be happy to pick this back up later on, but right now things are too busy.

**Comment by iceman1001** [comment]
ping!

**Comment by adryd325** [comment]
I'm unlikely to work on this further. If I do i'll open a new PR

**Pull request closed without merging**
