### PR TITLE
Rework hitag2 read/write help

### PR DESCRIPTION
**Pull request by ViRb3**
And add default keys

### CODE REVIEW

**Comment by iceman1001** [comment]
Hm.. so there is no write / read on hitag S?

**Comment by ViRb3** [comment]
Sure there is? I only reworded the help text.

**Comment by iceman1001** [comment]
Because your rewording removes "read all pages" etc from the help text..
So it that not true anymore?

**Comment by ViRb3** [comment]
Oh, no, it's still valid. I just assumed that if it's under the `read` command it's obvious that it reads, and under the `write` command it writes. Think I should add that back to the help?

**Comment by iceman1001** [comment]
Not sure its much clearer with your suggested changes.  
hitag reader...   acting as a reader doesn't mean read ,  read all pages,  etc..

**Comment by ViRb3** [comment]
Sure, I'll re-write it to be clearer.

**Comment by ViRb3** [comment]
How does that look like? :)

**Comment by doegox** [comment]
looks good, thanks

**Comment by pwpiwi** [comment]
Are there other default passwords? It doesn't work for me on a brand new Hitag2 tag:
```
[usb] pm3 --> lf hitag reader
Hitag reader functions
Usage: lf hitag reader [h] <reader function #>
Options:
       h               This help
   HitagS (0*)
      01 <nr> <ar>     Read all pages, challenge mode
      02 <key>         Read all pages, crypto mode. Set key=0 for no auth
   Hitag1 (1*)
      Not implemented
   Hitag2 (2*)
      21 <password>    Read all pages, password mode. Default: 4D494B52 ("MIKR")
      22 <nr> <ar>     Read all pages, challenge mode
      23 <key>         Read all pages, crypto mode. Key format: ISK high + ISK low. Default: 4F4E4D494B52 ("ONMIKR")
      25               Test recorded authentications
      26               Just read UID
[usb] pm3 --> lf hitag reader 21 4d494b52
#db# List identifier in password mode
#db# Password failed!
[usb] pm3 --> lf hitag reader 26
[+] Valid Hitag2 tag found - UID: aa8e6b11
```

**Comment by iceman1001** [comment]
Better to use forum for questions.

**Comment by ViRb3** [comment]
@pwpiwi those are the only default keys I'm afraid. I can confirm they work on my new Hitag2 cards. The distance and placement of the tag to the antenna is incredibly important, try moving it around and retrying the read.

**Comment by pwpiwi** [comment]
Indeed, I could make it work after some fiddling! While `lf hitag 26` works at different distances, `lf hitag 23` is more sensitive to distance (which makes me think that sending is the issue rather than receiving). In general, possible distances are quite low compared to commercial LF readers.

**Comment by doegox** [comment]
Indeed @pwpiwi lf hitag suffers from two problems: reading distance (while manually I could achieve much large distances) and last bit wrong/missing, see https://github.com/RfidResearchGroup/proxmark3/issues/124 and https://github.com/RfidResearchGroup/proxmark3/issues/240

**Comment by ViRb3** [comment]
@pwpiwi any chance your could send that upstream hitag love back to this repo? I could use your refactor if I'm doing more work on hitag.

**Comment by pwpiwi** [comment]
No need to send the latest changes from official to RRG. The PR adds latest additions (password write) formatting and refactoring from RRG to official. 😃

**Comment by ViRb3** [comment]
I meant your touches, e.g. the commands extracted to the protocols header. That's good stuff :)

**Comment by pwpiwi** [comment]
I had added this more or less for documentation only. Feel free to copy & paste. As discussed in #18 there is no easy way to reuse PRs and/or commits.

**Pull request merged**
