### PR TITLE
Added Vigik/Blackhat keys, corrected some issues/dups

### PR DESCRIPTION
**Pull request by UberGuidoZ**
Vigik Source: https://pastebin.com/JRBfjvsi
Tracked to https://play.google.com/store/apps/details?id=fr.badgevigik.scanbadge
Website of Vigik included in commit above

Blackhat Source: Flipper Community

The only info provided was an MFC key used for badge hacking (might be Blackhat badge)

Original PR (now amended) https://github.com/RfidResearchGroup/proxmark3/pull/1742

Signed-off-by: UberGuidoZ [57457139+UberGuidoZ@users.noreply.github.com](mailto:57457139+UberGuidoZ@users.noreply.github.com)

### CODE REVIEW

**Comment by UberGuidoZ** [comment]
Skipping the changelog but feel free to update it if desired =)

**Comment by UberGuidoZ** [comment]
@iceman1001 Added keys verified by @quantum-x as well as some newly discovered iGuard Simple keys.

**Comment by UberGuidoZ** [comment]
Further review removed 2 duplicates plus added some other missing keys.

Full/Current list from Flipper community maintained here: https://github.com/UberGuidoZ/Flipper/blob/main/NFC/mf_classic_dict/Non-RRG_Keys_Only.nfc

**Comment by iceman1001** [comment]
Thanks for the effort to make it neat and clean and with adding some context  !

**Comment by UberGuidoZ** [comment]
Thanks for all you do! Happy to contribute.

**Pull request merged**
