### PR TITLE
Add the needed qt package on ArchLinux

### PR DESCRIPTION
**Pull request by slurdge**
qt5-base is enough on my Arch

### CODE REVIEW

**Comment by doegox** [comment]
ok we trust you :)

**Comment by iceman1001** [comment]
I was just about to say that the instructions used another package name.. 
We use both these ones in the document.
yaourt  vs pacman

I never tried Archlinux,  so excuse my question,  but do they do the same thing?

**Comment by slurdge** [comment]
Almost. "pacman -S" is the equivalent of "apt install", gets official packages.
yaourt is a wrapper around pacman and makepkg. makepkg is used to build packages from community (AUR packages).

**Comment by slurdge** [comment]
Oh. And I made a typo. It's "-Sy" (y == yes) not "-Su"

**Comment by iceman1001** [comment]
thats your area of expertise...   *nix ppl unite!

**Pull request merged**
